// Generated by Claude.
// Page for editing an existing library
import { useState, useEffect, useCallback } from 'react';
import { useNavigation } from '@/navigation';
import { useLibraries } from '@/state';
import { useToast } from '@/components/Toast';
import { Input } from '@/components/ui/Input';
import { Textarea } from '@/components/ui/Textarea';
import { Label } from '@/components/ui/Label';

const EditLibrary = () => {
  const { setOptions, goBack, params } = useNavigation();
  const { updateLibrary } = useLibraries();
  const toast = useToast();

  const library = params?.library;

  const [name, setName] = useState(library?.name || '');
  const [description, setDescription] = useState(library?.description || '');
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Name is required, max 20 chars
  const isValid = name.trim().length > 0 && name.trim().length <= 20;

  // Check if there are changes
  const hasChanges =
    name.trim() !== (library?.name || '') ||
    description.trim() !== (library?.description || '');

  const handleSave = useCallback(async () => {
    if (!isValid || isSubmitting || !library) return;

    setIsSubmitting(true);
    try {
      await updateLibrary(library.id, {
        name: name.trim(),
        description: description.trim(),
      });
      goBack();
    } catch (err) {
      toast.error(err.message || 'Failed to update library');
    } finally {
      setIsSubmitting(false);
    }
  }, [isValid, isSubmitting, library, name, description, updateLibrary, goBack, toast]);

  // Set up header with library name as title and Done button
  useEffect(() => {
    setOptions({
      title: library?.name || 'Edit Library',
      headerRight: (
        <button
          onClick={handleSave}
          disabled={!isValid || !hasChanges || isSubmitting}
          className={`text-sm font-medium ${
            isValid && hasChanges && !isSubmitting ? 'text-primary' : 'text-muted-foreground'
          }`}
        >
          {isSubmitting ? 'Saving...' : 'Done'}
        </button>
      ),
    });
  }, [setOptions, library, handleSave, isValid, hasChanges, isSubmitting]);

  if (!library) {
    return (
      <div className="flex h-full items-center justify-center p-4">
        <p className="text-muted-foreground">Library not found</p>
      </div>
    );
  }

  return (
    <div className="p-4 space-y-6">
      <div className="space-y-2">
        <Label htmlFor="library-name">Name</Label>
        <Input
          id="library-name"
          value={name}
          onChange={(e) => setName(e.target.value)}
          placeholder="My Library"
          maxLength={20}
          autoCapitalize="words"
          autoComplete="off"
          autoFocus
        />
        <p className="text-xs text-muted-foreground text-right">
          {name.length}/20
        </p>
      </div>

      <div className="space-y-2">
        <Label htmlFor="library-description">Description (optional)</Label>
        <Textarea
          id="library-description"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          placeholder="A short description"
          maxLength={100}
          rows={3}
        />
        <p className="text-xs text-muted-foreground text-right">
          {description.length}/100
        </p>
      </div>
    </div>
  );
};

export default EditLibrary;
