// Generated by Claude.
import { useAuth } from '@/auth/AuthContext';
import { Button } from '@/components/ui/Button';

const Home = () => {
  const { user, signOut } = useAuth();

  return (
    <div className="flex min-h-svh items-center justify-center">
      <div className="text-center space-y-4">
        <h1 className="text-4xl font-bold tracking-tight">Alexandria</h1>
        <p className="text-muted-foreground">
          Welcome! Your library dashboard is coming soon.
        </p>
        <p className="text-sm text-muted-foreground">
          User ID: {user?.id}
        </p>
        <Button variant="outline" onClick={signOut}>
          Sign out
        </Button>
      </div>
    </div>
  );
};

export default Home;
