// Generated by Claude.
// Libraries tab: displays owned and shared libraries
import { useEffect, useCallback } from 'react';
import { useLibraries } from '@/state';
import LibraryCard from '@/components/LibraryCard';
import PullToRefresh from '@/components/PullToRefresh';
import { Loader2, LibraryBig, AlertCircle } from 'lucide-react';

const Libraries = () => {
  const { ownedLibraries, sharedLibraries, isLoading, error, fetchLibraries } = useLibraries();

  // Fetch libraries on mount
  useEffect(() => {
    fetchLibraries();
  }, [fetchLibraries]);

  const handleRefresh = useCallback(async () => {
    await fetchLibraries();
  }, [fetchLibraries]);

  const handleLibraryClick = (library) => {
    // TODO: Navigate to library detail
    console.log('Library clicked:', library);
  };

  // Initial loading state (no data yet)
  const hasData = ownedLibraries.length > 0 || sharedLibraries.length > 0;
  if (isLoading && !hasData) {
    return (
      <div className="flex h-full items-center justify-center p-4">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  // Error state (no data)
  if (error && !hasData) {
    return (
      <PullToRefresh onRefresh={handleRefresh} className="h-full">
        <div className="flex h-full flex-col items-center justify-center gap-2 p-4 text-center">
          <AlertCircle className="h-8 w-8 text-destructive" />
          <p className="text-sm text-muted-foreground">{error}</p>
          <p className="text-xs text-muted-foreground">Pull down to retry</p>
        </div>
      </PullToRefresh>
    );
  }

  // Empty state
  if (!hasData) {
    return (
      <PullToRefresh onRefresh={handleRefresh} className="h-full">
        <div className="flex h-full flex-col items-center justify-center gap-2 p-4 text-center">
          <LibraryBig className="h-12 w-12 text-muted-foreground/50" />
          <p className="text-lg font-medium">No libraries yet</p>
          <p className="text-sm text-muted-foreground">
            Create your first library to start organizing your books.
          </p>
        </div>
      </PullToRefresh>
    );
  }

  return (
    <PullToRefresh onRefresh={handleRefresh} className="h-full">
      <div className="p-4 space-y-6">
        {/* Owned libraries */}
        {ownedLibraries.length > 0 && (
          <section>
            <h2 className="mb-3 text-sm font-medium text-muted-foreground uppercase tracking-wide">
              My Libraries
            </h2>
            <div className="space-y-2">
              {ownedLibraries.map((library) => (
                <LibraryCard
                  key={library.id}
                  library={library}
                  onClick={handleLibraryClick}
                />
              ))}
            </div>
          </section>
        )}

        {/* Shared libraries */}
        {sharedLibraries.length > 0 && (
          <section>
            <h2 className="mb-3 text-sm font-medium text-muted-foreground uppercase tracking-wide">
              Shared with me
            </h2>
            <div className="space-y-2">
              {sharedLibraries.map((library) => (
                <LibraryCard
                  key={library.id}
                  library={library}
                  onClick={handleLibraryClick}
                />
              ))}
            </div>
          </section>
        )}
      </div>
    </PullToRefresh>
  );
};

export default Libraries;
