// Generated by Claude.
// Libraries tab: displays owned and shared libraries
import { useEffect, useCallback, useState, useRef } from 'react';
import { Plus, Loader2, LibraryBig, AlertCircle } from 'lucide-react';
import { useLibraries } from '@/state';
import { useNavigation } from '@/navigation';
import LibraryCard from '@/components/LibraryCard';
import PullToRefresh from '@/components/PullToRefresh';
import LibraryActionsSheet from '@/components/LibraryActionsSheet';
import { useToast } from '@/components/Toast';

const Libraries = () => {
  const { ownedLibraries, sharedLibraries, isLoading, error, hasLoaded, fetchLibraries, deleteLibrary, shareLibrary } = useLibraries();
  const { setOptions, navigate } = useNavigation();
  const toast = useToast();
  const [selectedLibrary, setSelectedLibrary] = useState(null);
  const [isActionsOpen, setIsActionsOpen] = useState(false);
  const [isActionLoading, setIsActionLoading] = useState(false);
  const fetchingRef = useRef(false); // Guard against React Strict Mode double-call

  // Set up header "+" button
  useEffect(() => {
    setOptions({
      headerRight: (
        <button
          onClick={() => navigate('newLibrary', { push: true })}
          className="flex h-9 w-9 items-center justify-center rounded-md text-foreground hover:bg-accent"
          aria-label="Add library"
        >
          <Plus className="h-5 w-5" />
        </button>
      ),
    });
  }, [setOptions, navigate]);

  // Fetch libraries on mount if not already loaded
  // - hasLoaded: prevents refetch when returning to cached screen
  // - fetchingRef: guards against React Strict Mode double-call
  useEffect(() => {
    if (!hasLoaded && !fetchingRef.current) {
      fetchingRef.current = true;
      fetchLibraries();
    }
  }, [hasLoaded, fetchLibraries]);

  const handleRefresh = useCallback(async () => {
    await fetchLibraries();
  }, [fetchLibraries]);

  const handleLibraryClick = (library) => {
    navigate('libraryContent', { push: true, params: { library } });
  };

  const handleLongPress = useCallback((library) => {
    setSelectedLibrary(library);
    setIsActionsOpen(true);
  }, []);

  const handleCloseActions = useCallback(() => {
    setIsActionsOpen(false);
    setSelectedLibrary(null);
    setIsActionLoading(false);
  }, []);

  // Handle action from sheet
  // data parameter contains extra info like { email } for share action
  const handleAction = useCallback(async (action, library, data) => {
    switch (action) {
      case 'edit':
        handleCloseActions();
        navigate('editLibrary', { push: true, params: { library } });
        break;
      case 'share':
        setIsActionLoading(true);
        try {
          await shareLibrary(library.id, data.email);
          handleCloseActions();
        } catch (err) {
          toast.error(err.message || 'Failed to share library');
          setIsActionLoading(false);
        }
        break;
      case 'unshare':
        handleCloseActions();
        navigate('unshareLibrary', { push: true, params: { library } });
        break;
      case 'delete':
        setIsActionLoading(true);
        try {
          await deleteLibrary(library.id);
          handleCloseActions();
        } catch (err) {
          toast.error(err.message || 'Failed to delete library');
          setIsActionLoading(false);
        }
        break;
      default:
        break;
    }
  }, [navigate, deleteLibrary, shareLibrary, toast, handleCloseActions]);

  // Determine content based on state
  const hasData = ownedLibraries.length > 0 || sharedLibraries.length > 0;

  const renderContent = () => {
    // Initial loading state (no data yet)
    if (isLoading && !hasData) {
      return (
        <div className="flex h-full items-center justify-center p-4">
          <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
        </div>
      );
    }

    // Error state (no data)
    if (error && !hasData) {
      return (
        <PullToRefresh onRefresh={handleRefresh} className="h-full">
          <div className="flex h-full flex-col items-center justify-center gap-2 p-4 text-center">
            <AlertCircle className="h-8 w-8 text-destructive" />
            <p className="text-sm text-muted-foreground">{error}</p>
            <p className="text-xs text-muted-foreground">Pull down to retry</p>
          </div>
        </PullToRefresh>
      );
    }

    // Empty state
    if (!hasData) {
      return (
        <PullToRefresh onRefresh={handleRefresh} className="h-full">
          <div className="flex h-full flex-col items-center justify-center gap-2 p-4 text-center">
            <LibraryBig className="h-12 w-12 text-muted-foreground/50" />
            <p className="text-lg font-medium">No libraries yet</p>
            <p className="text-sm text-muted-foreground">
              Create your first library to start organizing your books.
            </p>
          </div>
        </PullToRefresh>
      );
    }

    // Libraries list
    return (
      <PullToRefresh onRefresh={handleRefresh} className="h-full">
        <div className="p-4 space-y-6">
          {/* Owned libraries */}
          {ownedLibraries.length > 0 && (
            <section>
              <h2 className="mb-3 text-sm font-medium text-muted-foreground uppercase tracking-wide">
                My Libraries
              </h2>
              <div className="space-y-2">
                {ownedLibraries.map((library) => (
                  <LibraryCard
                    key={library.id}
                    library={library}
                    onClick={handleLibraryClick}
                    onLongPress={handleLongPress}
                  />
                ))}
              </div>
            </section>
          )}

          {/* Shared libraries */}
          {sharedLibraries.length > 0 && (
            <section>
              <h2 className="mb-3 text-sm font-medium text-muted-foreground uppercase tracking-wide">
                Shared with me
              </h2>
              <div className="space-y-2">
                {sharedLibraries.map((library) => (
                  <LibraryCard
                    key={library.id}
                    library={library}
                    onClick={handleLibraryClick}
                  />
                ))}
              </div>
            </section>
          )}
        </div>
      </PullToRefresh>
    );
  };

  return (
    <>
      {renderContent()}
      <LibraryActionsSheet
        library={selectedLibrary}
        isOpen={isActionsOpen}
        onClose={handleCloseActions}
        onAction={handleAction}
        isLoading={isActionLoading}
      />
    </>
  );
};

export default Libraries;
