// Generated by Claude.
// Libraries tab: placeholder for library management
const Libraries = () => {
  return (
    <div className="flex h-full items-center justify-center p-4">
      <div className="text-center space-y-2">
        <p className="text-2xl">📚</p>
        <h2 className="text-xl font-semibold">Libraries</h2>
        <p className="text-muted-foreground">
          Your libraries will appear here.
        </p>
      </div>
    </div>
  );
};

export default Libraries;
