// Generated by Claude.
import { Clock } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { useAuth } from '@/auth/AuthContext';

const PendingApproval = () => {
  const { signOut, user } = useAuth();

  return (
    <div className="flex flex-col items-center justify-center min-h-screen p-6 bg-background">
      <div className="flex flex-col items-center text-center max-w-sm">
        <div className="w-20 h-20 rounded-full bg-amber-100 dark:bg-amber-900/30 flex items-center justify-center mb-6">
          <Clock className="w-10 h-10 text-amber-600 dark:text-amber-400" />
        </div>

        <h1 className="text-2xl font-semibold mb-2">Pending Approval</h1>

        <p className="text-muted-foreground mb-6">
          Your account is awaiting administrator approval. You'll be able to access
          Alexandria once your account has been approved.
        </p>

        {(user?.email || user?.username) && (
          <p className="text-sm text-muted-foreground mb-6">
            Signed in as <span className="font-medium">{user.email || user.username}</span>
          </p>
        )}

        <Button variant="outline" onClick={signOut} className="w-full">
          Sign Out
        </Button>
      </div>
    </div>
  );
};

export default PendingApproval;
