// Generated by Claude.
// Search page - fuzzy search across all books with recent searches
import { useState, useEffect, useRef, useCallback } from 'react';
import { Search as SearchIcon, X, Loader2, Clock, BookOpen, Library, Users } from 'lucide-react';
import { searchApi } from '@/api';
import { useNavigation } from '@/navigation';
import { useAuth } from '@/auth/AuthContext';
import { Input } from '@/components/ui/Input';

const RECENT_SEARCHES_KEY = 'alexandria_recent_searches';
const MAX_RECENT_SEARCHES = 5;
const MIN_SEARCH_LENGTH = 3;
const DEBOUNCE_MS = 300;

// Persist recent searches in localStorage (PWA-compatible)
const getRecentSearches = () => {
  try {
    const stored = localStorage.getItem(RECENT_SEARCHES_KEY);
    return stored ? JSON.parse(stored) : [];
  } catch {
    return [];
  }
};

const saveRecentSearch = (term) => {
  try {
    const recent = getRecentSearches();
    // Remove duplicate if exists, add to front
    const filtered = recent.filter((s) => s.toLowerCase() !== term.toLowerCase());
    const updated = [term, ...filtered].slice(0, MAX_RECENT_SEARCHES);
    localStorage.setItem(RECENT_SEARCHES_KEY, JSON.stringify(updated));
    return updated;
  } catch {
    return [];
  }
};

const clearRecentSearches = () => {
  try {
    localStorage.removeItem(RECENT_SEARCHES_KEY);
  } catch {
    // Ignore storage errors
  }
};

// Search result card with library name - custom layout to avoid overlap
const SearchResultCard = ({ book, onClick, isShared }) => {
  const hasImage = book.pictureUrl || book.picture;
  const authors = book.authors?.join(', ') || '';

  return (
    <button
      onClick={() => onClick(book)}
      className="w-full flex gap-3 p-2 rounded-md bg-muted/30 text-left transition-colors hover:bg-accent/50 active:bg-accent select-none"
    >
      {/* Book cover */}
      <div className="shrink-0 w-10 h-14 rounded bg-muted flex items-center justify-center overflow-hidden">
        {hasImage ? (
          <img
            src={book.pictureUrl || `data:image/webp;base64,${book.picture}`}
            alt={book.title}
            className="w-full h-full object-cover"
          />
        ) : (
          <BookOpen className="h-5 w-5 text-muted-foreground/50" />
        )}
      </div>

      {/* Book info */}
      <div className="flex-1 min-w-0 flex flex-col justify-center">
        <p className="text-sm font-medium truncate">{book.title}</p>
        {authors && (
          <p className="text-xs text-muted-foreground truncate">{authors}</p>
        )}
        {/* Library name with shared indicator */}
        {book.libraryName && (
          <p className="text-xs text-muted-foreground/70 truncate mt-0.5 flex items-center gap-1">
            {isShared ? (
              <Users className="h-3 w-3 shrink-0 text-blue-500" />
            ) : (
              <Library className="h-3 w-3 shrink-0" />
            )}
            {book.libraryName}
            {isShared && <span className="text-blue-500">(shared)</span>}
          </p>
        )}
      </div>
    </button>
  );
};

const Search = () => {
  const { navigate } = useNavigation();
  const { user } = useAuth();
  const [query, setQuery] = useState('');
  const [results, setResults] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);
  const [hasSearched, setHasSearched] = useState(false);
  const [recentSearches, setRecentSearches] = useState(getRecentSearches);
  const inputRef = useRef(null);
  const debounceRef = useRef(null);

  // Auto-focus input on mount
  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  // Debounced search effect
  useEffect(() => {
    // Clear any pending search
    if (debounceRef.current) {
      clearTimeout(debounceRef.current);
    }

    const trimmed = query.trim();

    // Reset state if query too short
    if (trimmed.length < MIN_SEARCH_LENGTH) {
      setResults([]);
      setHasSearched(false);
      setError(null);
      return;
    }

    // Debounce the search
    debounceRef.current = setTimeout(async () => {
      setIsLoading(true);
      setError(null);

      try {
        // Split query into terms for fuzzy search
        const terms = trimmed.split(/\s+/).filter(Boolean);
        const response = await searchApi.search(terms);
        setResults(response.results || []);
        setHasSearched(true);

        // Save to recent searches on successful search
        setRecentSearches(saveRecentSearch(trimmed));
      } catch (err) {
        setError(err.message || 'Search failed');
        setResults([]);
      } finally {
        setIsLoading(false);
      }
    }, DEBOUNCE_MS);

    return () => {
      if (debounceRef.current) {
        clearTimeout(debounceRef.current);
      }
    };
  }, [query]);

  const handleClear = useCallback(() => {
    setQuery('');
    setResults([]);
    setHasSearched(false);
    setError(null);
    inputRef.current?.focus();
  }, []);

  const handleRecentClick = useCallback((term) => {
    setQuery(term);
  }, []);

  const handleClearRecent = useCallback(() => {
    clearRecentSearches();
    setRecentSearches([]);
  }, []);

  // Check if a book is from a shared library (owner is not current user)
  const isSharedBook = useCallback((book) => {
    return book.ownerId && book.ownerId !== user?.id;
  }, [user?.id]);

  // Navigate to book detail with library context from search result
  const handleBookClick = useCallback((book) => {
    // Construct library-like object from search result fields
    const library = {
      id: book.libraryId,
      name: book.libraryName,
      // If ownerId differs from current user, it's a shared library
      sharedFrom: isSharedBook(book) ? book.ownerId : null,
    };
    navigate('bookDetail', { push: true, params: { library, book } });
  }, [navigate, isSharedBook]);

  const showRecentSearches = query.trim().length < MIN_SEARCH_LENGTH && recentSearches.length > 0;

  return (
    <div className="absolute inset-0 flex flex-col">
      {/* Search input - sticky */}
      <div className="shrink-0 p-4 border-b border-border bg-background">
        <div className="relative">
          <SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            ref={inputRef}
            type="text"
            placeholder="Search books..."
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            className="pl-9 pr-9"
          />
          {query && (
            <button
              onClick={handleClear}
              className="absolute right-2 top-1/2 -translate-y-1/2 p-1 rounded-full hover:bg-accent"
              aria-label="Clear search"
            >
              <X className="h-4 w-4 text-muted-foreground" />
            </button>
          )}
        </div>
        {query.trim().length > 0 && query.trim().length < MIN_SEARCH_LENGTH && (
          <p className="mt-2 text-xs text-muted-foreground">
            Type at least {MIN_SEARCH_LENGTH} characters to search
          </p>
        )}
      </div>

      {/* Content area */}
      <div className="flex-1 overflow-y-auto">
        {/* Loading indicator */}
        {isLoading && (
          <div className="flex items-center justify-center p-8">
            <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
          </div>
        )}

        {/* Error state */}
        {error && !isLoading && (
          <div className="p-4 text-center">
            <p className="text-sm text-destructive">{error}</p>
            <button
              onClick={() => setQuery(query)}
              className="mt-2 text-sm text-primary underline"
            >
              Retry
            </button>
          </div>
        )}

        {/* Recent searches */}
        {showRecentSearches && !isLoading && (
          <div className="p-4">
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-sm font-medium text-muted-foreground">Recent searches</h3>
              <button
                onClick={handleClearRecent}
                className="text-xs text-muted-foreground hover:text-foreground"
              >
                Clear
              </button>
            </div>
            <div className="space-y-2">
              {recentSearches.map((term, index) => (
                <button
                  key={index}
                  onClick={() => handleRecentClick(term)}
                  className="flex items-center gap-2 w-full p-2 rounded-md hover:bg-accent text-left"
                >
                  <Clock className="h-4 w-4 text-muted-foreground shrink-0" />
                  <span className="text-sm truncate">{term}</span>
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Empty state - no query */}
        {!query.trim() && !showRecentSearches && !isLoading && (
          <div className="flex flex-col items-center justify-center h-full p-4 text-center">
            <SearchIcon className="h-12 w-12 text-muted-foreground/50 mb-4" />
            <p className="text-lg font-medium">Search your books</p>
            <p className="text-sm text-muted-foreground mt-1">
              Find books by title, author, or ISBN
            </p>
          </div>
        )}

        {/* No results */}
        {hasSearched && results.length === 0 && !isLoading && !error && (
          <div className="flex flex-col items-center justify-center p-8 text-center">
            <BookOpen className="h-12 w-12 text-muted-foreground/50 mb-4" />
            <p className="text-lg font-medium">No books found</p>
            <p className="text-sm text-muted-foreground mt-1">
              Try different keywords or check the spelling
            </p>
          </div>
        )}

        {/* Search results */}
        {results.length > 0 && !isLoading && (
          <div className="p-4">
            <p className="text-sm text-muted-foreground mb-3">
              {results.length} {results.length === 1 ? 'result' : 'results'}
            </p>
            <div className="space-y-2">
              {results.map((book) => (
                <SearchResultCard
                  key={book.id}
                  book={book}
                  onClick={handleBookClick}
                  isShared={isSharedBook(book)}
                />
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default Search;
