// Generated by Claude.
// Search tab: placeholder for book/library search
const Search = () => {
  return (
    <div className="flex h-full items-center justify-center p-4">
      <div className="text-center space-y-2">
        <p className="text-2xl">🔍</p>
        <h2 className="text-xl font-semibold">Search</h2>
        <p className="text-muted-foreground">
          Search for books and libraries here.
        </p>
      </div>
    </div>
  );
};

export default Search;
