// Generated by Claude.
// Settings tab: placeholder for app settings
import { useAuth } from '@/auth/AuthContext';
import { Button } from '@/components/ui/Button';

const Settings = () => {
  const { user, signOut } = useAuth();

  return (
    <div className="flex h-full items-center justify-center p-4">
      <div className="text-center space-y-4">
        <p className="text-2xl">⚙️</p>
        <h2 className="text-xl font-semibold">Settings</h2>
        <p className="text-sm text-muted-foreground">
          User ID: {user?.id}
        </p>
        <Button variant="outline" onClick={signOut}>
          Sign out
        </Button>
      </div>
    </div>
  );
};

export default Settings;
