// Generated by Claude.
// Page for sharing a library with another user
import { useState, useEffect, useCallback } from 'react';
import { useNavigation } from '@/navigation';
import { useLibraries } from '@/state';
import { useToast } from '@/components/Toast';
import { Input } from '@/components/ui/Input';
import { Label } from '@/components/ui/Label';

const ShareLibrary = () => {
  const { setOptions, goBack, params } = useNavigation();
  const { shareLibrary } = useLibraries();
  const toast = useToast();

  const library = params?.library;

  const [email, setEmail] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Basic email validation
  const isValidEmail = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim());

  const handleShare = useCallback(async () => {
    if (!isValidEmail || isSubmitting || !library) return;

    setIsSubmitting(true);
    try {
      await shareLibrary(library.id, email.trim());
      goBack();
    } catch (err) {
      toast.error(err.message || 'Failed to share library');
    } finally {
      setIsSubmitting(false);
    }
  }, [isValidEmail, isSubmitting, library, email, shareLibrary, goBack, toast]);

  // Set up header with library name as title and Done button
  useEffect(() => {
    setOptions({
      title: library?.name || 'Share Library',
      headerRight: (
        <button
          onClick={handleShare}
          disabled={!isValidEmail || isSubmitting}
          className={`text-sm font-medium ${
            isValidEmail && !isSubmitting ? 'text-primary' : 'text-muted-foreground'
          }`}
        >
          {isSubmitting ? 'Sharing...' : 'Done'}
        </button>
      ),
    });
  }, [setOptions, library, handleShare, isValidEmail, isSubmitting]);

  if (!library) {
    return (
      <div className="flex h-full items-center justify-center p-4">
        <p className="text-muted-foreground">Library not found</p>
      </div>
    );
  }

  return (
    <div className="p-4 space-y-6">
      <div className="space-y-2">
        <Label htmlFor="share-email">User</Label>
        <Input
          id="share-email"
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          placeholder="user@example.com"
          autoCapitalize="none"
          autoComplete="email"
          autoCorrect="off"
          autoFocus
        />
        <p className="text-xs text-muted-foreground">
          Enter the email address of the user you want to share this library with.
          They will have read-only access.
        </p>
      </div>
    </div>
  );
};

export default ShareLibrary;
