// Generated by Claude.
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Eye, EyeOff } from 'lucide-react';
import { useAuth } from '@/auth/AuthContext';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Label } from '@/components/ui/Label';
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui/Card';

// Password validation - returns error message or null if valid
const validatePassword = (pw) => {
  if (pw.length < 8) return 'Must be at least 8 characters';
  if (!/[a-z]/.test(pw)) return 'Must include a lowercase letter';
  if (!/[A-Z]/.test(pw)) return 'Must include an uppercase letter';
  if (!/[0-9]/.test(pw)) return 'Must include a number';
  if (!/[^a-zA-Z0-9]/.test(pw)) return 'Must include a symbol';
  return null;
};

const SignUp = () => {
  const [email, setEmail] = useState('');
  const [displayName, setDisplayName] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [passwordTouched, setPasswordTouched] = useState(false);
  const [error, setError] = useState(null);
  const [submitting, setSubmitting] = useState(false);
  const [success, setSuccess] = useState(false);
  const { signUp } = useAuth();

  const passwordError = password.length > 0 ? validatePassword(password) : null;
  const passwordValid = password.length > 0 && !passwordError;
  const passwordsMatch = password === confirmPassword && confirmPassword.length > 0;
  const displayNameValid = displayName.length === 0 || displayName.length <= 20;
  const canSubmit = email && passwordValid && passwordsMatch && displayNameValid;

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!canSubmit) return;

    setError(null);
    setSubmitting(true);
    try {
      await signUp(email, password, displayName || undefined);
      setSuccess(true);
    } catch (err) {
      // Map Cognito error codes to user-friendly messages
      if (err.name === 'UsernameExistsException') {
        setError('An account with this email already exists');
      } else if (err.name === 'InvalidParameterException') {
        setError(err.message || 'Invalid input');
      } else {
        setError(err.message || 'Sign up failed');
      }
    } finally {
      setSubmitting(false);
    }
  };

  // Success state - show pending approval message
  if (success) {
    return (
      <div className="flex min-h-svh items-center justify-center px-4 animate-fade-in">
        <Card className="w-full max-w-sm">
          <CardHeader className="text-center">
            <CardTitle className="text-2xl">Account Created</CardTitle>
            <CardDescription>Your registration is pending approval</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4 text-center">
            <p className="text-sm text-muted-foreground">
              An administrator will review your request. You will be able to sign in once your account is approved.
            </p>
          </CardContent>
          <CardFooter>
            <Link to="/login" className="w-full">
              <Button variant="outline" className="w-full">
                Back to Sign in
              </Button>
            </Link>
          </CardFooter>
        </Card>
      </div>
    );
  }

  return (
    <div className="flex min-h-svh items-center justify-center px-4 py-4 animate-fade-in">
      <Card className="w-full max-w-sm">
        <CardHeader className="text-center pb-2">
          <CardTitle className="text-xl">Create Account</CardTitle>
          <CardDescription>Sign up to manage your libraries</CardDescription>
        </CardHeader>
        <form onSubmit={handleSubmit}>
          <CardContent className="space-y-3 pt-0">
            {error && (
              <p className="text-sm text-destructive text-center">{error}</p>
            )}
            <div className="space-y-1">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                autoComplete="email"
                autoCapitalize="none"
                autoCorrect="off"
                required
              />
            </div>
            <div className="space-y-1">
              <div className="flex items-baseline justify-between">
                <Label htmlFor="displayName">Display Name</Label>
                <span className={`text-xs text-muted-foreground ${displayName.length === 0 ? 'invisible' : ''}`}>
                  {displayName.length}/20
                </span>
              </div>
              <Input
                id="displayName"
                value={displayName}
                onChange={(e) => setDisplayName(e.target.value)}
                maxLength={20}
                autoCapitalize="words"
                autoCorrect="off"
                placeholder="Optional"
              />
            </div>
            <div className="space-y-1">
              <Label htmlFor="password">Password</Label>
              <div className="relative">
                <Input
                  id="password"
                  type={showPassword ? 'text' : 'password'}
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  onBlur={() => setPasswordTouched(true)}
                  autoComplete="new-password"
                  autoCapitalize="none"
                  autoCorrect="off"
                  required
                  className="pr-10"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-2 top-1/2 -translate-y-1/2 p-1 rounded-md text-muted-foreground hover:text-foreground hover:bg-accent"
                  aria-label={showPassword ? 'Hide password' : 'Show password'}
                >
                  {showPassword ? (
                    <EyeOff className="h-4 w-4" />
                  ) : (
                    <Eye className="h-4 w-4" />
                  )}
                </button>
              </div>
              <p className={`text-xs text-destructive ${!passwordTouched || !passwordError ? 'invisible' : ''}`}>
                {passwordError || 'Valid'}
              </p>
            </div>
            <div className="space-y-1">
              <Label htmlFor="confirmPassword">Confirm Password</Label>
              <div className="relative">
                <Input
                  id="confirmPassword"
                  type={showConfirmPassword ? 'text' : 'password'}
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                  autoComplete="new-password"
                  autoCapitalize="none"
                  autoCorrect="off"
                  required
                  className="pr-10"
                />
                <button
                  type="button"
                  onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                  className="absolute right-2 top-1/2 -translate-y-1/2 p-1 rounded-md text-muted-foreground hover:text-foreground hover:bg-accent"
                  aria-label={showConfirmPassword ? 'Hide password' : 'Show password'}
                >
                  {showConfirmPassword ? (
                    <EyeOff className="h-4 w-4" />
                  ) : (
                    <Eye className="h-4 w-4" />
                  )}
                </button>
              </div>
              <p className={`text-xs text-destructive ${confirmPassword.length === 0 || passwordsMatch ? 'invisible' : ''}`}>
                Passwords do not match
              </p>
            </div>
          </CardContent>
          <CardFooter className="flex flex-col gap-2 pt-2">
            <Button type="submit" className="w-full" disabled={!canSubmit || submitting}>
              {submitting ? 'Creating account...' : 'Create account'}
            </Button>
            <p className="text-sm text-muted-foreground text-center">
              Already have an account?{' '}
              <Link to="/login" className="text-foreground underline underline-offset-4 hover:text-primary">
                Sign in
              </Link>
            </p>
          </CardFooter>
        </form>
      </Card>
    </div>
  );
};

export default SignUp;
