// Generated by Claude.
// Reusable bottom sheet component with header (title, cancel, done)
import { useEffect } from 'react';
import { cn } from '@/lib/utils';

const BottomSheet = ({
  isOpen,
  onClose,
  onDone,
  title,
  cancelLabel = 'Cancel',
  doneLabel = 'Done',
  doneDisabled = false,
  children,
}) => {
  // Prevent body scroll when sheet is open
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [isOpen]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex flex-col justify-end">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/50 animate-in fade-in duration-200"
        onClick={onClose}
      />

      {/* Sheet */}
      <div
        className={cn(
          'relative bg-background rounded-t-xl min-h-[50vh] max-h-[90vh] flex flex-col',
          'animate-in slide-in-from-bottom duration-300'
        )}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-border">
          <button
            onClick={onClose}
            className="text-sm text-primary font-medium min-w-[60px] text-left"
          >
            {cancelLabel}
          </button>
          <h2 className="text-base font-semibold">{title}</h2>
          <button
            onClick={onDone}
            disabled={doneDisabled}
            className={cn(
              'text-sm font-medium min-w-[60px] text-right',
              doneDisabled ? 'text-muted-foreground' : 'text-primary'
            )}
          >
            {doneLabel}
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-4">
          {children}
        </div>
      </div>
    </div>
  );
};

export default BottomSheet;
