// Generated by Claude.
// Reusable bottom sheet component with header (title, cancel, done)
// Supports enter/exit fade animations
import { useEffect, useState } from 'react';
import { cn } from '@/lib/utils';

const ANIMATION_DURATION = 200; // ms

const BottomSheet = ({
  isOpen,
  onClose,
  onDone,
  title,
  cancelLabel,
  doneLabel,
  doneDisabled = false,
  children,
}) => {
  // Track mounting state for exit animation
  const [isVisible, setIsVisible] = useState(false);
  const [isAnimating, setIsAnimating] = useState(false);

  // Handle open/close with animation
  useEffect(() => {
    if (isOpen) {
      setIsVisible(true);
      // Small delay to ensure mount before animation starts
      requestAnimationFrame(() => setIsAnimating(true));
    } else if (isVisible) {
      // Start exit animation
      setIsAnimating(false);
      // Unmount after animation completes
      const timer = setTimeout(() => setIsVisible(false), ANIMATION_DURATION);
      return () => clearTimeout(timer);
    }
  }, [isOpen, isVisible]);

  // Prevent body scroll when sheet is open
  useEffect(() => {
    if (isVisible) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [isVisible]);

  if (!isVisible) return null;

  return (
    <div className="fixed inset-0 z-[60] flex flex-col justify-end">
      {/* Backdrop with fade */}
      <div
        className={cn(
          'absolute inset-0 bg-black/50 transition-opacity',
          isAnimating ? 'opacity-100' : 'opacity-0'
        )}
        style={{ transitionDuration: `${ANIMATION_DURATION}ms` }}
        onClick={onClose}
      />

      {/* Sheet with slide + fade */}
      <div
        className={cn(
          'relative bg-background rounded-t-xl min-h-[50vh] max-h-[90vh] flex flex-col',
          'transition-all',
          isAnimating
            ? 'opacity-100 translate-y-0'
            : 'opacity-0 translate-y-8'
        )}
        style={{ transitionDuration: `${ANIMATION_DURATION}ms` }}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-border">
          {cancelLabel ? (
            <button
              onClick={onClose}
              className="text-sm text-primary font-medium min-w-[60px] text-left"
            >
              {cancelLabel}
            </button>
          ) : (
            <div className="min-w-[60px]" />
          )}
          <h2 className="text-base font-semibold">{title}</h2>
          {doneLabel ? (
            <button
              onClick={onDone}
              disabled={doneDisabled}
              className={cn(
                'text-sm font-medium min-w-[60px] text-right',
                doneDisabled ? 'text-muted-foreground' : 'text-primary'
              )}
            >
              {doneLabel}
            </button>
          ) : (
            <div className="min-w-[60px]" />
          )}
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-4 pb-[calc(1rem+env(safe-area-inset-bottom))]">
          {children}
        </div>
      </div>
    </div>
  );
};

export default BottomSheet;
