// Generated by Claude.
// Bottom sheet for selecting a collection (or "None")
// Used in EditBook/EditVideo to assign items to collections
import { Check, Loader2, FolderOpen } from 'lucide-react';
import BottomSheet from './BottomSheet';
import { cn } from '@/lib/utils';

const CollectionPickerSheet = ({
  isOpen,
  onClose,
  collections,
  selectedId,
  onSelect,
  isLoading,
}) => {
  const handleSelect = (collection) => {
    onSelect(collection);
    onClose();
  };

  return (
    <BottomSheet isOpen={isOpen} onClose={onClose} title="Select Collection">
      <div className="space-y-1">
        {isLoading ? (
          <div className="flex items-center justify-center py-8">
            <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
          </div>
        ) : (
          <>
            {/* "None" option to remove from collection */}
            <button
              onClick={() => handleSelect(null)}
              className={cn(
                'w-full flex items-center gap-3 px-4 py-3 rounded-lg transition-colors text-left',
                selectedId === null ? 'bg-primary/10' : 'hover:bg-muted'
              )}
            >
              <div className="w-8 h-8 rounded-full bg-muted flex items-center justify-center">
                <FolderOpen className="h-4 w-4 text-muted-foreground" />
              </div>
              <span className="flex-1 font-medium">None</span>
              {selectedId === null && (
                <Check className="h-5 w-5 text-primary" />
              )}
            </button>

            {/* Collection list */}
            {collections.map((collection) => (
              <button
                key={collection.id}
                onClick={() => handleSelect(collection)}
                className={cn(
                  'w-full flex items-center gap-3 px-4 py-3 rounded-lg transition-colors text-left',
                  selectedId === collection.id ? 'bg-primary/10' : 'hover:bg-muted'
                )}
              >
                <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center">
                  <FolderOpen className="h-4 w-4 text-primary" />
                </div>
                <span className="flex-1 font-medium">{collection.name}</span>
                {selectedId === collection.id && (
                  <Check className="h-5 w-5 text-primary" />
                )}
              </button>
            ))}

            {/* Empty state */}
            {collections.length === 0 && (
              <p className="text-center text-muted-foreground py-4 text-sm">
                No collections in this library
              </p>
            )}
          </>
        )}
      </div>
    </BottomSheet>
  );
};

export default CollectionPickerSheet;
