// Generated by Claude.
// SVG illustration of an empty bookshelf for empty states
// Minimalist sketch style with warm tones matching Modern Bookshelf theme

const EmptyBookshelf = ({ className = '' }) => {
  return (
    <svg
      viewBox="0 0 120 100"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
    >
      {/* Bookshelf frame - warm wood tone */}
      <rect
        x="10"
        y="15"
        width="100"
        height="70"
        rx="2"
        stroke="currentColor"
        strokeWidth="2"
        strokeOpacity="0.3"
        fill="none"
      />

      {/* Middle shelf */}
      <line
        x1="10"
        y1="50"
        x2="110"
        y2="50"
        stroke="currentColor"
        strokeWidth="2"
        strokeOpacity="0.25"
      />

      {/* A few books leaning on top shelf - sketch style */}
      <g opacity="0.4">
        {/* Tall book */}
        <rect
          x="20"
          y="22"
          width="8"
          height="26"
          rx="1"
          fill="currentColor"
          fillOpacity="0.15"
          stroke="currentColor"
          strokeWidth="1"
        />
        {/* Medium book, slightly tilted */}
        <rect
          x="30"
          y="28"
          width="7"
          height="20"
          rx="1"
          fill="currentColor"
          fillOpacity="0.1"
          stroke="currentColor"
          strokeWidth="1"
          transform="rotate(-5 30 28)"
        />
        {/* Small book */}
        <rect
          x="42"
          y="34"
          width="6"
          height="14"
          rx="1"
          fill="currentColor"
          fillOpacity="0.08"
          stroke="currentColor"
          strokeWidth="1"
        />
      </g>

      {/* Empty space indicators - dashed outlines where books could go */}
      <g strokeDasharray="3 3" opacity="0.2">
        {/* Top shelf empty spots */}
        <rect
          x="60"
          y="25"
          width="10"
          height="23"
          rx="1"
          stroke="currentColor"
          strokeWidth="1"
          fill="none"
        />
        <rect
          x="75"
          y="27"
          width="8"
          height="21"
          rx="1"
          stroke="currentColor"
          strokeWidth="1"
          fill="none"
        />
        <rect
          x="88"
          y="24"
          width="12"
          height="24"
          rx="1"
          stroke="currentColor"
          strokeWidth="1"
          fill="none"
        />

        {/* Bottom shelf empty spots */}
        <rect
          x="18"
          y="56"
          width="14"
          height="26"
          rx="1"
          stroke="currentColor"
          strokeWidth="1"
          fill="none"
        />
        <rect
          x="38"
          y="58"
          width="10"
          height="24"
          rx="1"
          stroke="currentColor"
          strokeWidth="1"
          fill="none"
        />
        <rect
          x="54"
          y="55"
          width="12"
          height="27"
          rx="1"
          stroke="currentColor"
          strokeWidth="1"
          fill="none"
        />
        <rect
          x="72"
          y="57"
          width="9"
          height="25"
          rx="1"
          stroke="currentColor"
          strokeWidth="1"
          fill="none"
        />
        <rect
          x="87"
          y="56"
          width="13"
          height="26"
          rx="1"
          stroke="currentColor"
          strokeWidth="1"
          fill="none"
        />
      </g>

      {/* Decorative plant pot on shelf - adds warmth */}
      <g opacity="0.35">
        <ellipse
          cx="52"
          cy="48"
          rx="4"
          ry="2"
          fill="currentColor"
        />
        <rect
          x="49"
          y="42"
          width="6"
          height="6"
          rx="1"
          fill="currentColor"
          fillOpacity="0.8"
        />
        {/* Plant leaves */}
        <path
          d="M52 42 Q54 38 52 35 Q50 38 52 42"
          fill="currentColor"
          fillOpacity="0.5"
        />
        <path
          d="M52 42 Q56 40 58 36"
          stroke="currentColor"
          strokeWidth="1.5"
          fill="none"
          strokeLinecap="round"
        />
        <path
          d="M52 42 Q48 39 46 35"
          stroke="currentColor"
          strokeWidth="1.5"
          fill="none"
          strokeLinecap="round"
        />
      </g>
    </svg>
  );
};

export default EmptyBookshelf;
