// Generated by Claude.
// Reusable image component with fade-in on load
// Provides smooth loading experience for covers and posters
import { useState, useCallback } from 'react';
import { cn } from '@/lib/utils';

const FadeImage = ({
  src,
  alt,
  className,
  fallback = null,
  ...props
}) => {
  const [loaded, setLoaded] = useState(false);
  const [error, setError] = useState(false);

  const handleLoad = useCallback(() => {
    setLoaded(true);
  }, []);

  const handleError = useCallback(() => {
    setError(true);
  }, []);

  // Show fallback if error or no src
  if (error || !src) {
    return fallback;
  }

  return (
    <img
      src={src}
      alt={alt}
      onLoad={handleLoad}
      onError={handleError}
      className={cn(
        'transition-opacity duration-300',
        loaded ? 'opacity-100' : 'opacity-0',
        className
      )}
      {...props}
    />
  );
};

export default FadeImage;
