// Generated by Claude.
// Reusable image component with fade-in on load
// Provides smooth loading experience for covers and posters
// Supports fallbackSrc to try alternative URL before showing fallback component
import { useState, useCallback } from 'react';
import { cn } from '@/lib/utils';

const FadeImage = ({
  src,
  fallbackSrc,
  alt,
  className,
  fallback = null,
  ...props
}) => {
  const [loaded, setLoaded] = useState(false);
  const [error, setError] = useState(false);
  const [useFallbackSrc, setUseFallbackSrc] = useState(false);

  const handleLoad = useCallback(() => {
    setLoaded(true);
  }, []);

  const handleError = useCallback(() => {
    // If primary src fails and we have a fallbackSrc, try it
    if (!useFallbackSrc && fallbackSrc) {
      setUseFallbackSrc(true);
      setLoaded(false);
    } else {
      setError(true);
    }
  }, [useFallbackSrc, fallbackSrc]);

  // Show fallback component if all URLs failed or no src
  if (error || !src) {
    return fallback;
  }

  const currentSrc = useFallbackSrc ? fallbackSrc : src;

  return (
    <img
      src={currentSrc}
      alt={alt}
      onLoad={handleLoad}
      onError={handleError}
      className={cn(
        'transition-opacity duration-300',
        loaded ? 'opacity-100' : 'opacity-0',
        className
      )}
      {...props}
    />
  );
};

export default FadeImage;
