// Generated by Claude.
// Action sheet for library actions (Edit, Share, Unshare, Delete)
import { useEffect } from 'react';
import { Pencil, Share2, UserMinus, Trash2 } from 'lucide-react';
import { cn } from '@/lib/utils';

const LibraryActionsSheet = ({ library, isOpen, onClose, onAction }) => {
  if (!library) return null;

  const isShared = library.sharedTo?.length > 0;

  // Prevent body scroll when sheet is open
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [isOpen]);

  if (!isOpen) return null;

  const handleAction = (action) => {
    onClose();
    onAction?.(action, library);
  };

  return (
    <div className="fixed inset-0 z-50 flex flex-col justify-end">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/50 animate-in fade-in duration-200"
        onClick={onClose}
      />

      {/* Sheet */}
      <div
        className={cn(
          'relative bg-background rounded-t-xl',
          'animate-in slide-in-from-bottom duration-300'
        )}
      >
        {/* Library name header */}
        <div className="px-4 py-3 border-b border-border text-center">
          <p className="font-medium truncate">{library.name}</p>
        </div>

        {/* Actions */}
        <div className="py-2">
          <button
            onClick={() => handleAction('edit')}
            className="w-full flex items-center gap-3 px-4 py-3 hover:bg-accent active:bg-accent transition-colors"
          >
            <Pencil className="h-5 w-5 text-muted-foreground" />
            <span>Edit</span>
          </button>

          <button
            onClick={() => handleAction('share')}
            className="w-full flex items-center gap-3 px-4 py-3 hover:bg-accent active:bg-accent transition-colors"
          >
            <Share2 className="h-5 w-5 text-muted-foreground" />
            <span>Share</span>
          </button>

          {isShared && (
            <button
              onClick={() => handleAction('unshare')}
              className="w-full flex items-center gap-3 px-4 py-3 hover:bg-accent active:bg-accent transition-colors"
            >
              <UserMinus className="h-5 w-5 text-muted-foreground" />
              <span>Unshare</span>
            </button>
          )}

          <button
            onClick={() => handleAction('delete')}
            className="w-full flex items-center gap-3 px-4 py-3 hover:bg-destructive/10 active:bg-destructive/10 transition-colors text-destructive"
          >
            <Trash2 className="h-5 w-5" />
            <div className="flex flex-col items-start">
              <span>Delete</span>
              <span className="text-xs text-destructive/70">This action cannot be undone</span>
            </div>
          </button>
        </div>

        {/* Cancel button */}
        <div className="p-4 pt-2 border-t border-border">
          <button
            onClick={onClose}
            className="w-full py-3 rounded-lg bg-secondary text-secondary-foreground font-medium hover:bg-secondary/80 transition-colors"
          >
            Cancel
          </button>
        </div>
      </div>
    </div>
  );
};

export default LibraryActionsSheet;
