// Generated by Claude.
// Grid-style library card for Modern Bookshelf layout
// Shows library initial as visual identifier (like contact avatars)
// Supports long press for actions on owned libraries
import { useRef, useCallback, useState } from 'react';
import { Users, UserCheck } from 'lucide-react';
import { cn } from '@/lib/utils';

const LONG_PRESS_DURATION = 500;
const LIFT_DELAY = 150; // Start lift animation earlier than long press
const STAGGER_DELAY = 50;

// Get library initial for avatar display
const getInitial = (name) => name?.charAt(0)?.toUpperCase() || '?';

const LibraryCard = ({ library, onClick, onLongPress, isSelected = false, index }) => {
  const isSharedFromOther = !!library.sharedFrom;
  const isSharedToOthers = library.sharedTo?.length > 0;
  const pressTimer = useRef(null);
  const liftTimer = useRef(null);
  const isLongPress = useRef(false);
  const [isLifting, setIsLifting] = useState(false);

  // Card is lifted during long press OR while selected (action sheet open)
  const showLift = isLifting || isSelected;

  const handleTouchStart = useCallback(() => {
    isLongPress.current = false;

    // Start lift animation early (visual feedback)
    if (!isSharedFromOther && onLongPress) {
      liftTimer.current = setTimeout(() => {
        setIsLifting(true);
      }, LIFT_DELAY);
    }

    // Trigger long press action
    pressTimer.current = setTimeout(() => {
      isLongPress.current = true;
      setIsLifting(false); // Reset lift when action triggers
      if (!isSharedFromOther && onLongPress) {
        onLongPress(library);
      }
    }, LONG_PRESS_DURATION);
  }, [library, isSharedFromOther, onLongPress]);

  const handleTouchEnd = useCallback(() => {
    if (pressTimer.current) {
      clearTimeout(pressTimer.current);
      pressTimer.current = null;
    }
    if (liftTimer.current) {
      clearTimeout(liftTimer.current);
      liftTimer.current = null;
    }
    setIsLifting(false);
  }, []);

  const handleClick = useCallback(() => {
    // Don't trigger click if it was a long press
    if (!isLongPress.current) {
      onClick?.(library);
    }
  }, [library, onClick]);

  // Staggered animation style
  const animationStyle = index != null
    ? { animationDelay: `${index * STAGGER_DELAY}ms` }
    : undefined;

  return (
    <button
      onClick={handleClick}
      onTouchStart={handleTouchStart}
      onTouchEnd={handleTouchEnd}
      onTouchCancel={handleTouchEnd}
      onContextMenu={(e) => {
        // Prevent context menu on long press, trigger action instead
        if (!isSharedFromOther && onLongPress) {
          e.preventDefault();
          onLongPress(library);
        }
      }}
      style={animationStyle}
      className={cn(
        // Grid card: square-ish, centered content with glassmorphism
        'relative flex flex-col items-center justify-center p-4 rounded-2xl text-center select-none',
        'aspect-[4/3] min-h-[120px]',
        // Glassmorphism: frosted glass effect
        'bg-[var(--glass-bg)] backdrop-blur-xl',
        'border border-[var(--glass-border)]',
        // Subtle inner glow at top edge
        'shadow-[var(--card-shadow),inset_0_1px_0_0_var(--glass-border)]',
        // Transitions
        'transition-[background-color,box-shadow,transform,border-color] duration-200',
        // Hover: lift up with glow (disabled during lift)
        !showLift && 'hover:shadow-[var(--card-shadow-hover),inset_0_1px_0_0_var(--glass-border),0_0_20px_var(--accent-glow)]',
        !showLift && 'hover:border-primary/20',
        !showLift && 'active:scale-[0.97]',
        // Long press lift state (during press or while action sheet open)
        showLift && 'card-lifting',
        // Staggered fade-in animation
        index != null && 'animate-fade-in-up'
      )}
    >
      {/* Shared indicator badge - top right corner */}
      {(isSharedFromOther || isSharedToOthers) && (
        <div className="absolute top-2.5 right-2.5 p-1.5 rounded-full bg-primary/10 backdrop-blur-sm">
          {isSharedFromOther ? (
            <UserCheck className="h-3.5 w-3.5 text-primary/70" />
          ) : (
            <Users className="h-3.5 w-3.5 text-primary/70" />
          )}
        </div>
      )}

      {/* Library initial avatar - glowing accent */}
      <div className="mb-2 w-12 h-12 rounded-full flex items-center justify-center text-lg font-semibold bg-primary/15 text-primary border border-primary/20 shadow-[0_0_12px_var(--accent-glow)]">
        {getInitial(library.name)}
      </div>

      {/* Library name */}
      <span className="font-medium text-sm leading-tight line-clamp-2 max-w-full px-1">
        {library.name}
      </span>

      {/* Item count or shared by */}
      <span className="text-xs text-muted-foreground mt-1 w-full px-1 truncate">
        {isSharedFromOther ? (
          // Show only username part of email (before @) for cleaner display
          `by ${library.sharedFrom.split('@')[0]}`
        ) : (
          `${library.totalItems} ${library.totalItems === 1 ? 'item' : 'items'}`
        )}
      </span>
    </button>
  );
};

export default LibraryCard;
