// Generated by Claude.
// Compact library card with different styles for owned/shared libraries
import { Users, UserCheck, ChevronRight } from 'lucide-react';
import { cn } from '@/lib/utils';

const LibraryCard = ({ library, onClick }) => {
  const isSharedFromOther = !!library.sharedFrom;
  const isSharedToOthers = library.sharedTo?.length > 0;

  return (
    <button
      onClick={() => onClick?.(library)}
      className={cn(
        'w-full flex items-center gap-3 p-3 rounded-lg border text-left transition-colors',
        'hover:bg-accent/50 active:bg-accent',
        isSharedFromOther
          ? 'border-blue-200 bg-blue-50/50 dark:border-blue-900 dark:bg-blue-950/30'
          : 'border-border bg-card'
      )}
    >
      {/* Content */}
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2">
          <span className="font-medium truncate">{library.name}</span>
          {/* Shared indicators */}
          {isSharedFromOther && (
            <span className="inline-flex items-center gap-1 text-xs text-blue-600 dark:text-blue-400">
              <UserCheck className="h-3 w-3" />
            </span>
          )}
          {isSharedToOthers && (
            <span className="inline-flex items-center gap-1 text-xs text-muted-foreground">
              <Users className="h-3 w-3" />
            </span>
          )}
        </div>

        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          {isSharedFromOther ? (
            <span className="truncate">
              Shared by {library.sharedFrom}
            </span>
          ) : (
            <>
              <span>{library.totalItems} {library.totalItems === 1 ? 'item' : 'items'}</span>
              {isSharedToOthers && (
                <>
                  <span className="text-border">·</span>
                  <span className="truncate">
                    Shared with {library.sharedTo.length} {library.sharedTo.length === 1 ? 'user' : 'users'}
                  </span>
                </>
              )}
            </>
          )}
        </div>
      </div>

      {/* Chevron */}
      <ChevronRight className="h-5 w-5 shrink-0 text-muted-foreground" />
    </button>
  );
};

export default LibraryCard;
