// Generated by Claude.
// Grid-style library card for Modern Bookshelf layout
// Compact square card with centered content
// Supports long press for actions on owned libraries
import { useRef, useCallback } from 'react';
import { Users, UserCheck, Library } from 'lucide-react';
import { cn } from '@/lib/utils';

const LONG_PRESS_DURATION = 500;
const STAGGER_DELAY = 50; // ms per item for staggered animation

const LibraryCard = ({ library, onClick, onLongPress, index }) => {
  const isSharedFromOther = !!library.sharedFrom;
  const isSharedToOthers = library.sharedTo?.length > 0;
  const pressTimer = useRef(null);
  const isLongPress = useRef(false);

  const handleTouchStart = useCallback(() => {
    isLongPress.current = false;
    pressTimer.current = setTimeout(() => {
      isLongPress.current = true;
      // Only trigger long press for owned libraries
      if (!isSharedFromOther && onLongPress) {
        onLongPress(library);
      }
    }, LONG_PRESS_DURATION);
  }, [library, isSharedFromOther, onLongPress]);

  const handleTouchEnd = useCallback(() => {
    if (pressTimer.current) {
      clearTimeout(pressTimer.current);
      pressTimer.current = null;
    }
  }, []);

  const handleClick = useCallback(() => {
    // Don't trigger click if it was a long press
    if (!isLongPress.current) {
      onClick?.(library);
    }
  }, [library, onClick]);

  // Staggered animation style
  const animationStyle = index != null
    ? { animationDelay: `${index * STAGGER_DELAY}ms` }
    : undefined;

  return (
    <button
      onClick={handleClick}
      onTouchStart={handleTouchStart}
      onTouchEnd={handleTouchEnd}
      onTouchCancel={handleTouchEnd}
      onContextMenu={(e) => {
        // Prevent context menu on long press, trigger action instead
        if (!isSharedFromOther && onLongPress) {
          e.preventDefault();
          onLongPress(library);
        }
      }}
      style={animationStyle}
      className={cn(
        // Grid card: square-ish, centered content
        'relative flex flex-col items-center justify-center p-4 rounded-xl border text-center select-none',
        'aspect-[4/3] min-h-[120px]',
        'transition-[background-color,box-shadow,transform] duration-200',
        'hover:bg-accent/50 active:bg-accent active:scale-[0.98]',
        isSharedFromOther
          ? 'border-green-300 bg-green-50/50 dark:border-green-800 dark:bg-green-950/30 shadow-[var(--card-shadow)]'
          : 'border-border bg-card shadow-[var(--card-shadow)] hover:shadow-[var(--card-shadow-hover)]',
        // Staggered fade-in animation
        index != null && 'animate-fade-in-up'
      )}
    >
      {/* Shared indicator badge - top right corner */}
      {(isSharedFromOther || isSharedToOthers) && (
        <div className={cn(
          'absolute top-2 right-2 p-1 rounded-full',
          isSharedFromOther
            ? 'bg-green-100 dark:bg-green-900/50'
            : 'bg-muted'
        )}>
          {isSharedFromOther ? (
            <UserCheck className="h-3.5 w-3.5 text-green-700 dark:text-green-400" />
          ) : (
            <Users className="h-3.5 w-3.5 text-muted-foreground" />
          )}
        </div>
      )}

      {/* Library icon */}
      <div className={cn(
        'mb-2 p-2.5 rounded-lg',
        isSharedFromOther
          ? 'bg-green-100 dark:bg-green-900/50'
          : 'bg-muted'
      )}>
        <Library className={cn(
          'h-6 w-6',
          isSharedFromOther
            ? 'text-green-700 dark:text-green-400'
            : 'text-muted-foreground'
        )} />
      </div>

      {/* Library name */}
      <span className="font-medium text-sm leading-tight line-clamp-2 max-w-full px-1">
        {library.name}
      </span>

      {/* Item count or shared by */}
      <span className="text-xs text-muted-foreground mt-1 w-full px-1 truncate">
        {isSharedFromOther ? (
          // Show only username part of email (before @) for cleaner display
          `by ${library.sharedFrom.split('@')[0]}`
        ) : (
          `${library.totalItems} ${library.totalItems === 1 ? 'book' : 'books'}`
        )}
      </span>
    </button>
  );
};

export default LibraryCard;
