// Generated by Claude.
// Bottom sheet for creating a new collection
import { useState, useEffect, useRef } from 'react';
import { Loader2 } from 'lucide-react';
import BottomSheet from './BottomSheet';
import { Input } from './ui/Input';
import { Button } from './ui/Button';

const NewCollectionSheet = ({ isOpen, onClose, onSubmit, isLoading = false }) => {
  const [name, setName] = useState('');
  const inputRef = useRef(null);

  // Reset and focus input when sheet opens
  useEffect(() => {
    if (isOpen) {
      setName('');
      // Delay focus to allow sheet animation
      setTimeout(() => inputRef.current?.focus(), 100);
    }
  }, [isOpen]);

  const handleSubmit = (e) => {
    e.preventDefault();
    const trimmedName = name.trim();
    if (!trimmedName || isLoading) return;
    onSubmit?.(trimmedName);
  };

  const canSubmit = name.trim().length > 0 && !isLoading;

  return (
    <BottomSheet isOpen={isOpen} onClose={onClose} title="New Collection">
      <form onSubmit={handleSubmit} className="space-y-4">
        <Input
          ref={inputRef}
          type="text"
          value={name}
          onChange={(e) => setName(e.target.value)}
          placeholder="Collection name"
          maxLength={100}
          disabled={isLoading}
        />
        <Button
          type="submit"
          disabled={!canSubmit}
          className="w-full"
        >
          {isLoading ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin mr-2" />
              Creating...
            </>
          ) : (
            'Create Collection'
          )}
        </Button>
      </form>
    </BottomSheet>
  );
};

export default NewCollectionSheet;
