// Generated by Claude.
// Full-screen onboarding with swipeable cards and Lottie animations
import { useState, useRef, useEffect } from 'react';
import Lottie from 'lottie-react';
import { Book, ScanBarcode, FolderOpen, Share2 } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { cn } from '@/lib/utils';

// Vite glob import: loads all JSON files from animations folder
// Returns { './welcome.json': () => Promise<module>, ... }
const animationModules = import.meta.glob('@/assets/animations/*.json');

// Onboarding slides configuration
const SLIDES = [
  {
    id: 'welcome',
    title: 'Welcome to Alexandria',
    description: 'Your personal library to track books, videos, and manage lending.',
    icon: Book,
    animationKey: '/src/assets/animations/welcome.json',
    gradient: 'from-violet-500/20 to-purple-600/20',
  },
  {
    id: 'add',
    title: 'Add Items Easily',
    description: 'Scan ISBN barcodes for books, or snap a Blu-ray cover to auto-detect videos.',
    icon: ScanBarcode,
    animationKey: '/src/assets/animations/add-item.json',
    gradient: 'from-blue-500/20 to-cyan-500/20',
  },
  {
    id: 'collections',
    title: 'Organize with Collections',
    description: 'Group related items together. Create collections like "Favorites" or series.',
    icon: FolderOpen,
    animationKey: '/src/assets/animations/collections.json',
    gradient: 'from-emerald-500/20 to-teal-500/20',
  },
  {
    id: 'share',
    title: 'Share & Lend',
    description: 'Share your library with friends and keep track of who borrowed what.',
    icon: Share2,
    animationKey: '/src/assets/animations/share.json',
    gradient: 'from-amber-500/20 to-orange-500/20',
  },
];

/**
 * Onboarding component - Full-screen swipeable intro for first-time users
 * @param {{ onComplete: () => void }} props
 */
const Onboarding = ({ onComplete }) => {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [animations, setAnimations] = useState({});
  const [touchStart, setTouchStart] = useState(null);
  const [touchDelta, setTouchDelta] = useState(0);
  const [isDragging, setIsDragging] = useState(false);
  const containerRef = useRef(null);

  // Load Lottie animations dynamically via Vite's glob import
  useEffect(() => {
    const loadAnimations = async () => {
      const loaded = {};
      for (const slide of SLIDES) {
        // Find the matching module from glob import
        const moduleLoader = animationModules[slide.animationKey];
        if (moduleLoader) {
          try {
            const module = await moduleLoader();
            loaded[slide.id] = module.default;
          } catch {
            loaded[slide.id] = null;
          }
        } else {
          // Animation file not found - will use fallback icon
          loaded[slide.id] = null;
        }
      }
      setAnimations(loaded);
    };
    loadAnimations();
  }, []);

  // Touch handlers for swipe navigation
  const handleTouchStart = (e) => {
    setTouchStart(e.touches[0].clientX);
    setIsDragging(true);
  };

  const handleTouchMove = (e) => {
    if (!touchStart) return;
    const currentX = e.touches[0].clientX;
    const delta = currentX - touchStart;
    setTouchDelta(delta);
  };

  const handleTouchEnd = () => {
    if (!isDragging) return;

    const threshold = 50; // Minimum swipe distance

    if (touchDelta < -threshold && currentSlide < SLIDES.length - 1) {
      // Swipe left - next slide
      setCurrentSlide((prev) => prev + 1);
    } else if (touchDelta > threshold && currentSlide > 0) {
      // Swipe right - previous slide
      setCurrentSlide((prev) => prev - 1);
    }

    setTouchStart(null);
    setTouchDelta(0);
    setIsDragging(false);
  };

  // Navigation handlers
  const handleNext = () => {
    if (currentSlide < SLIDES.length - 1) {
      setCurrentSlide((prev) => prev + 1);
    } else {
      onComplete();
    }
  };

  const handleSkip = () => {
    onComplete();
  };

  const slide = SLIDES[currentSlide];
  const Icon = slide.icon;
  const isLastSlide = currentSlide === SLIDES.length - 1;

  return (
    <div
      ref={containerRef}
      className="fixed inset-0 z-50 flex flex-col bg-background"
      onTouchStart={handleTouchStart}
      onTouchMove={handleTouchMove}
      onTouchEnd={handleTouchEnd}
    >
      {/* Background gradient based on current slide */}
      <div
        className={cn(
          'absolute inset-0 bg-gradient-to-br transition-all duration-500',
          slide.gradient
        )}
      />

      {/* Skip button - top right */}
      <div className="relative z-10 flex justify-end p-4">
        <Button
          variant="ghost"
          size="sm"
          onClick={handleSkip}
          className="text-muted-foreground hover:text-foreground"
        >
          Skip
        </Button>
      </div>

      {/* Main content area */}
      <div className="relative z-10 flex flex-1 flex-col items-center justify-center px-8">
        {/* Animation or fallback icon */}
        <div
          className={cn(
            'mb-8 flex h-64 w-64 items-center justify-center transition-transform duration-300',
            isDragging && 'scale-95'
          )}
          style={{
            transform: isDragging ? `translateX(${touchDelta * 0.3}px)` : undefined,
          }}
        >
          {animations[slide.id] ? (
            <Lottie
              animationData={animations[slide.id]}
              loop
              className="h-full w-full"
            />
          ) : (
            // Fallback: glassmorphism circle with icon
            <div className="flex h-48 w-48 items-center justify-center rounded-full bg-[var(--glass-bg)] backdrop-blur-xl border border-[var(--glass-border)]">
              <Icon className="h-24 w-24 text-primary" strokeWidth={1.5} />
            </div>
          )}
        </div>

        {/* Text content */}
        <div
          className={cn(
            'text-center transition-all duration-300',
            isDragging && 'opacity-70'
          )}
          style={{
            transform: isDragging ? `translateX(${touchDelta * 0.2}px)` : undefined,
          }}
        >
          <h1 className="mb-4 text-2xl font-bold text-foreground">{slide.title}</h1>
          <p className="max-w-xs text-muted-foreground">{slide.description}</p>
        </div>
      </div>

      {/* Bottom section: dots + button */}
      <div className="relative z-10 flex flex-col items-center gap-6 pb-12">
        {/* Progress dots */}
        <div className="flex gap-2">
          {SLIDES.map((_, index) => (
            <button
              key={index}
              onClick={() => setCurrentSlide(index)}
              className={cn(
                'h-2 rounded-full transition-all duration-300',
                index === currentSlide
                  ? 'w-6 bg-primary'
                  : 'w-2 bg-muted-foreground/40 hover:bg-muted-foreground/60'
              )}
              aria-label={`Go to slide ${index + 1}`}
            />
          ))}
        </div>

        {/* Next/Get Started button */}
        <Button
          onClick={handleNext}
          className="min-w-[160px] rounded-full"
          size="lg"
        >
          {isLastSlide ? 'Get Started' : 'Next'}
        </Button>
      </div>

      {/* Swipe hint on first slide */}
      {currentSlide === 0 && (
        <div className="absolute bottom-32 left-1/2 -translate-x-1/2 animate-pulse text-xs text-muted-foreground">
          Swipe to navigate
        </div>
      )}
    </div>
  );
};

export default Onboarding;
