// Generated by Claude.
// Pull to refresh component for mobile-style refresh
import { useState, useRef, useCallback } from 'react';
import { Loader2 } from 'lucide-react';
import { cn } from '@/lib/utils';

const PULL_THRESHOLD = 80;

const PullToRefresh = ({ onRefresh, children, className }) => {
  const [pullDistance, setPullDistance] = useState(0);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const containerRef = useRef(null);
  const startY = useRef(0);
  const isPulling = useRef(false);

  const handleTouchStart = useCallback((e) => {
    const container = containerRef.current;
    // Only enable pull when scrolled to top
    if (container && container.scrollTop === 0) {
      startY.current = e.touches[0].clientY;
      isPulling.current = true;
    }
  }, []);

  const handleTouchMove = useCallback((e) => {
    if (!isPulling.current || isRefreshing) return;

    const currentY = e.touches[0].clientY;
    const diff = currentY - startY.current;

    // Only pull down, not up
    if (diff > 0) {
      // Apply resistance to make it feel natural
      const distance = Math.min(diff * 0.5, PULL_THRESHOLD * 1.5);
      setPullDistance(distance);
    }
  }, [isRefreshing]);

  const handleTouchEnd = useCallback(async () => {
    if (!isPulling.current) return;
    isPulling.current = false;

    if (pullDistance >= PULL_THRESHOLD && onRefresh) {
      setIsRefreshing(true);
      try {
        await onRefresh();
      } finally {
        setIsRefreshing(false);
      }
    }
    setPullDistance(0);
  }, [pullDistance, onRefresh]);

  const showIndicator = pullDistance > 0 || isRefreshing;
  const indicatorProgress = Math.min(pullDistance / PULL_THRESHOLD, 1);

  return (
    <div
      ref={containerRef}
      className={cn('h-full overflow-y-auto', className)}
      onTouchStart={handleTouchStart}
      onTouchMove={handleTouchMove}
      onTouchEnd={handleTouchEnd}
    >
      {/* Pull indicator */}
      <div
        className="flex items-center justify-center overflow-hidden transition-all"
        style={{ height: showIndicator ? Math.max(pullDistance, isRefreshing ? 48 : 0) : 0 }}
      >
        <Loader2
          className={cn(
            'h-6 w-6 text-muted-foreground transition-opacity',
            isRefreshing && 'animate-spin'
          )}
          style={{ opacity: isRefreshing ? 1 : indicatorProgress }}
        />
      </div>

      {children}
    </div>
  );
};

export default PullToRefresh;
