// Generated by Claude.
// Prompts user when a new PWA version is available
import { useRegisterSW } from 'virtual:pwa-register/react';
import { RefreshCw } from 'lucide-react';
import { cn } from '@/lib/utils';

const PWAUpdatePrompt = () => {
  const {
    needRefresh: [needRefresh],
    updateServiceWorker,
  } = useRegisterSW({
    // Check for updates every 60 seconds when app is open
    onRegisteredSW(swUrl, registration) {
      if (registration) {
        setInterval(() => {
          registration.update();
        }, 60 * 1000);
      }
    },
  });

  if (!needRefresh) return null;

  return (
    <div
      className={cn(
        'fixed top-4 left-4 right-4 z-[100]',
        'flex items-center gap-3 px-4 py-3 rounded-lg shadow-lg',
        'bg-primary text-primary-foreground',
        'animate-in slide-in-from-top-4 fade-in duration-300'
      )}
      role="alert"
    >
      <RefreshCw className="h-5 w-5 shrink-0" />
      <p className="flex-1 text-sm font-medium">New version available</p>
      <button
        onClick={() => updateServiceWorker(true)}
        className="shrink-0 px-3 py-1 text-sm font-medium bg-white/20 rounded-md hover:bg-white/30 transition-colors"
      >
        Update
      </button>
    </div>
  );
};

export default PWAUpdatePrompt;
