// Generated by Claude.
// Renders the Alexandria app icon SVGs to the PNG sizes the PWA/manifest needs.
// Run: yarn --cwd packages/web-client-v2 icons
import sharp from 'sharp';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const standard = readFileSync(resolve(root, 'assets/icon/alexandria-icon.svg'));
const maskable = readFileSync(resolve(root, 'assets/icon/alexandria-icon-maskable.svg'));
const out = (f) => resolve(root, 'public', f);

const jobs = [
  { svg: standard, size: 144, file: 'logo144.png' },
  { svg: standard, size: 180, file: 'logo180.png' },
  { svg: standard, size: 192, file: 'logo192.png' },
  { svg: standard, size: 512, file: 'logo512.png' },
  { svg: maskable, size: 512, file: 'logo512-maskable.png' },
  { svg: standard, size: 32, file: 'favicon-32x32.png' },
  { svg: standard, size: 16, file: 'favicon-16x16.png' },
];

for (const { svg, size, file } of jobs) {
  await sharp(svg, { density: 384 }).resize(size, size).png().toFile(out(file));
  console.log(`✓ ${file} (${size}×${size})`);
}
console.log('Done. Note: favicon.ico is left as-is (sharp does not emit .ico).');
