// Generated by Claude.
// Ported from the pre-refactor packages/cli/main.go (git history, HEAD).
// Only the Cognito/DynamoDB plumbing changed (now via internal/cognito,
// internal/dynamodb clients); the check logic and output text are unchanged.
package cmd

import (
	"context"
	"fmt"
	"strings"

	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/spf13/cobra"

	"alexandria.isnan.eu/cli/internal/cognito"
	"alexandria.isnan.eu/cli/internal/config"
	"alexandria.isnan.eu/cli/internal/dynamodb"
)

// Entity types matching backend persistence layer
const (
	TypeLibrary       = "LIBRARY"
	TypeSharedLibrary = "SHARED_LIBRARY"
	TypeBook          = "BOOK"
	TypeVideo         = "VIDEO"
	TypeEvent         = "EVENT"
	TypeCollection    = "COLLECTION"
)

// =============================================================================
// Consistency Check Implementation
// =============================================================================

// consistencyResult holds the results of all consistency checks
type consistencyResult struct {
	OrphanedSharedLibraries    []orphanedSharedLibrary
	OrphanedItems              []orphanedRecord
	OrphanedCollections        []orphanedRecord
	OrphanedItemEvents         []orphanedItemEvent
	ItemsWithMissingCollection []itemMissingCollection
	OrphanOwners               []orphanOwner
	LibraryCountMismatches     []countMismatch
	CollectionCountMismatches  []countMismatch
	DenormalizationDrifts      []denormDrift
}

type orphanedSharedLibrary struct {
	RecipientOwnerId string
	LibraryId        string
	SharedFromId     string
}

type orphanedRecord struct {
	OwnerId    string
	LibraryId  string
	RecordId   string
	RecordType string
}

type orphanedItemEvent struct {
	OwnerId   string
	LibraryId string
	ItemId    string
	EventSK   string
}

type itemMissingCollection struct {
	OwnerId      string
	LibraryId    string
	ItemId       string
	CollectionId string
}

type orphanOwner struct {
	OwnerId    string
	EntityType string
	RecordSK   string
}

type countMismatch struct {
	OwnerId    string
	RecordId   string
	RecordName string
	Expected   int
	Actual     int
}

type denormDrift struct {
	OwnerId     string
	ItemId      string
	Field       string
	ExpectedVal string
	ActualVal   string
}

// DynamoDB record structures for scanning
type dynamoRecord struct {
	PK             string  `dynamodbav:"PK"`
	SK             string  `dynamodbav:"SK"`
	EntityType     string  `dynamodbav:"EntityType"`
	OwnerId        string  `dynamodbav:"OwnerId"`
	LibraryId      string  `dynamodbav:"LibraryId"`
	LibraryName    string  `dynamodbav:"LibraryName"`
	CollectionId   *string `dynamodbav:"CollectionId"`
	CollectionName *string `dynamodbav:"CollectionName"`
	SharedFromId   string  `dynamodbav:"SharedFromId"`
	TotalItems     int     `dynamodbav:"TotalItems"`
	ItemCount      int     `dynamodbav:"ItemCount"`
	Name           string  `dynamodbav:"LibraryName"`    // For LIBRARY entities
	CollName       string  `dynamodbav:"CollectionName"` // For COLLECTION entities
}

var dataConsistencyCmd = &cobra.Command{
	Use:   "check-consistency",
	Short: "Check DynamoDB/Cognito data consistency",
	RunE: func(cmd *cobra.Command, args []string) error {
		cfg, err := config.Load(cfgFile)
		if err != nil {
			return fmt.Errorf("loading config: %w", err)
		}
		ctx := context.Background()

		cognitoClient, err := cognito.NewClient(ctx, cfg.Region, cfg.UserPoolID)
		if err != nil {
			return fmt.Errorf("creating Cognito client: %w", err)
		}
		ddb, err := dynamodb.NewClient(ctx, cfg.Region, cfg.TableName)
		if err != nil {
			return fmt.Errorf("creating DynamoDB client: %w", err)
		}

		// Preserve the original CLI's opening banner so operators see identical output.
		fmt.Println("Starting consistency check...")
		fmt.Println()

		fmt.Print("Loading Cognito users... ")
		users, err := cognitoClient.ListUsers(ctx)
		if err != nil {
			return fmt.Errorf("loading Cognito users: %w", err)
		}
		validOwnerIds := make(map[string]bool, len(users))
		for _, u := range users {
			if u.ID != "" {
				validOwnerIds[u.ID] = true
			}
		}
		fmt.Printf("%d users found\n", len(validOwnerIds))

		fmt.Print("Scanning DynamoDB table... ")
		rows, err := ddb.Scan(ctx, "", nil, nil)
		if err != nil {
			return fmt.Errorf("scanning DynamoDB: %w", err)
		}
		records := make([]dynamoRecord, 0, len(rows))
		for _, row := range rows {
			var r dynamoRecord
			if err := attributevalue.UnmarshalMap(row.Attributes, &r); err != nil {
				continue // skip malformed rows, as the original did
			}
			records = append(records, r)
		}
		fmt.Printf("%d records found\n\n", len(records))

		result := runConsistencyChecks(validOwnerIds, records)
		fmt.Println()
		printConsistencyResults(result)
		return nil
	},
}

func init() {
	dataCmd.AddCommand(dataConsistencyCmd)
}

// runConsistencyChecks is the old checkConsistency body, from the point after
// Cognito users and DynamoDB records are loaded. Kept as a pure function over
// (validOwnerIds, records) so it - and the extract* helpers it calls - stay
// unit-testable without needing live AWS clients.
func runConsistencyChecks(validOwnerIds map[string]bool, records []dynamoRecord) consistencyResult {
	// Build indexes for efficient lookups
	libraries := make(map[string]dynamoRecord)   // key: "ownerId#libraryId"
	collections := make(map[string]dynamoRecord) // key: "ownerId#libraryId#collectionId"
	items := make(map[string]dynamoRecord)       // key: "ownerId#libraryId#itemId"
	sharedLibraries := []dynamoRecord{}
	itemEvents := []dynamoRecord{}
	itemsByLibrary := make(map[string][]dynamoRecord)    // key: "ownerId#libraryId"
	itemsByCollection := make(map[string][]dynamoRecord) // key: "ownerId#libraryId#collectionId"

	for _, r := range records {
		switch r.EntityType {
		case TypeLibrary:
			libId := extractLibraryIdFromSK(r.SK)
			ownerId := extractOwnerIdFromPK(r.PK)
			libraries[ownerId+"#"+libId] = r
		case TypeCollection:
			libId, collId := extractLibraryAndCollectionIdFromSK(r.SK)
			ownerId := extractOwnerIdFromPK(r.PK)
			collections[ownerId+"#"+libId+"#"+collId] = r
		case TypeBook, TypeVideo:
			libId, itemId := extractLibraryAndItemIdFromSK(r.SK)
			ownerId := extractOwnerIdFromPK(r.PK)
			items[ownerId+"#"+libId+"#"+itemId] = r
			itemsByLibrary[ownerId+"#"+libId] = append(itemsByLibrary[ownerId+"#"+libId], r)
			if r.CollectionId != nil && *r.CollectionId != "" {
				itemsByCollection[ownerId+"#"+libId+"#"+*r.CollectionId] = append(itemsByCollection[ownerId+"#"+libId+"#"+*r.CollectionId], r)
			}
		case TypeSharedLibrary:
			sharedLibraries = append(sharedLibraries, r)
		case TypeEvent:
			itemEvents = append(itemEvents, r)
		}
	}

	result := consistencyResult{}

	// Check 1: Orphaned shared libraries
	fmt.Println("Checking orphaned shared libraries...")
	for _, sl := range sharedLibraries {
		libId := extractSharedLibraryIdFromSK(sl.SK)
		// Check if source library exists
		if _, exists := libraries[sl.SharedFromId+"#"+libId]; !exists {
			result.OrphanedSharedLibraries = append(result.OrphanedSharedLibraries, orphanedSharedLibrary{
				RecipientOwnerId: extractOwnerIdFromPK(sl.PK),
				LibraryId:        libId,
				SharedFromId:     sl.SharedFromId,
			})
		}
	}

	// Check 2: Orphaned items (library doesn't exist)
	fmt.Println("Checking orphaned items...")
	for key, item := range items {
		parts := strings.SplitN(key, "#", 3)
		ownerId, libId := parts[0], parts[1]
		if _, exists := libraries[ownerId+"#"+libId]; !exists {
			result.OrphanedItems = append(result.OrphanedItems, orphanedRecord{
				OwnerId:    ownerId,
				LibraryId:  libId,
				RecordId:   parts[2],
				RecordType: item.EntityType,
			})
		}
	}

	// Check 3: Orphaned collections (library doesn't exist)
	fmt.Println("Checking orphaned collections...")
	for key := range collections {
		parts := strings.SplitN(key, "#", 3)
		ownerId, libId := parts[0], parts[1]
		if _, exists := libraries[ownerId+"#"+libId]; !exists {
			result.OrphanedCollections = append(result.OrphanedCollections, orphanedRecord{
				OwnerId:    ownerId,
				LibraryId:  libId,
				RecordId:   parts[2],
				RecordType: TypeCollection,
			})
		}
	}

	// Check 4: Orphaned item events (item doesn't exist)
	fmt.Println("Checking orphaned item events...")
	for _, evt := range itemEvents {
		ownerId := extractOwnerIdFromPK(evt.PK)
		libId, itemId := extractLibraryAndItemIdFromEventSK(evt.SK)
		if _, exists := items[ownerId+"#"+libId+"#"+itemId]; !exists {
			result.OrphanedItemEvents = append(result.OrphanedItemEvents, orphanedItemEvent{
				OwnerId:   ownerId,
				LibraryId: libId,
				ItemId:    itemId,
				EventSK:   evt.SK,
			})
		}
	}

	// Check 5: Items with missing collection
	fmt.Println("Checking items with missing collections...")
	for key, item := range items {
		if item.CollectionId != nil && *item.CollectionId != "" {
			parts := strings.SplitN(key, "#", 3)
			ownerId, libId := parts[0], parts[1]
			if _, exists := collections[ownerId+"#"+libId+"#"+*item.CollectionId]; !exists {
				result.ItemsWithMissingCollection = append(result.ItemsWithMissingCollection, itemMissingCollection{
					OwnerId:      ownerId,
					LibraryId:    libId,
					ItemId:       parts[2],
					CollectionId: *item.CollectionId,
				})
			}
		}
	}

	// Check 6: Records with unknown owner
	fmt.Println("Checking records with unknown owners...")
	for _, r := range records {
		ownerId := extractOwnerIdFromPK(r.PK)
		if ownerId != "" && !validOwnerIds[ownerId] {
			result.OrphanOwners = append(result.OrphanOwners, orphanOwner{
				OwnerId:    ownerId,
				EntityType: r.EntityType,
				RecordSK:   r.SK,
			})
		}
	}

	// Check 7: Library TotalItems mismatch
	fmt.Println("Checking library item count mismatches...")
	for key, lib := range libraries {
		actualCount := len(itemsByLibrary[key])
		if lib.TotalItems != actualCount {
			parts := strings.SplitN(key, "#", 2)
			result.LibraryCountMismatches = append(result.LibraryCountMismatches, countMismatch{
				OwnerId:    parts[0],
				RecordId:   parts[1],
				RecordName: lib.LibraryName,
				Expected:   lib.TotalItems,
				Actual:     actualCount,
			})
		}
	}

	// Check 8: Collection ItemCount mismatch
	fmt.Println("Checking collection item count mismatches...")
	for key, coll := range collections {
		actualCount := len(itemsByCollection[key])
		if coll.ItemCount != actualCount {
			parts := strings.SplitN(key, "#", 3)
			result.CollectionCountMismatches = append(result.CollectionCountMismatches, countMismatch{
				OwnerId:    parts[0],
				RecordId:   parts[2],
				RecordName: coll.CollName,
				Expected:   coll.ItemCount,
				Actual:     actualCount,
			})
		}
	}

	// Check 9: Denormalization drift (LibraryName, CollectionName on items)
	fmt.Println("Checking denormalization drift...")
	for key, item := range items {
		parts := strings.SplitN(key, "#", 3)
		ownerId, libId := parts[0], parts[1]

		// Check library name
		if lib, exists := libraries[ownerId+"#"+libId]; exists {
			if item.LibraryName != lib.LibraryName {
				result.DenormalizationDrifts = append(result.DenormalizationDrifts, denormDrift{
					OwnerId:     ownerId,
					ItemId:      parts[2],
					Field:       "LibraryName",
					ExpectedVal: lib.LibraryName,
					ActualVal:   item.LibraryName,
				})
			}
		}

		// Check collection name
		if item.CollectionId != nil && *item.CollectionId != "" {
			if coll, exists := collections[ownerId+"#"+libId+"#"+*item.CollectionId]; exists {
				itemCollName := ""
				if item.CollectionName != nil {
					itemCollName = *item.CollectionName
				}
				if itemCollName != coll.CollName {
					result.DenormalizationDrifts = append(result.DenormalizationDrifts, denormDrift{
						OwnerId:     ownerId,
						ItemId:      parts[2],
						Field:       "CollectionName",
						ExpectedVal: coll.CollName,
						ActualVal:   itemCollName,
					})
				}
			}
		}
	}

	return result
}

// Key extraction helpers
func extractOwnerIdFromPK(pk string) string {
	// PK format: "owner#<ownerId>"
	if strings.HasPrefix(pk, "owner#") {
		return strings.TrimPrefix(pk, "owner#")
	}
	return ""
}

func extractLibraryIdFromSK(sk string) string {
	// SK format: "library#<libraryId>"
	if strings.HasPrefix(sk, "library#") {
		parts := strings.SplitN(sk, "#", 3)
		if len(parts) >= 2 {
			return parts[1]
		}
	}
	return ""
}

func extractSharedLibraryIdFromSK(sk string) string {
	// SK format: "shared-library#<libraryId>"
	if strings.HasPrefix(sk, "shared-library#") {
		return strings.TrimPrefix(sk, "shared-library#")
	}
	return ""
}

func extractLibraryAndCollectionIdFromSK(sk string) (string, string) {
	// SK format: "library#<libraryId>#collection#<collectionId>"
	parts := strings.Split(sk, "#")
	if len(parts) >= 4 && parts[0] == "library" && parts[2] == "collection" {
		return parts[1], parts[3]
	}
	return "", ""
}

func extractLibraryAndItemIdFromSK(sk string) (string, string) {
	// SK format: "library#<libraryId>#item#<itemId>"
	parts := strings.Split(sk, "#")
	if len(parts) >= 4 && parts[0] == "library" && parts[2] == "item" {
		return parts[1], parts[3]
	}
	return "", ""
}

func extractLibraryAndItemIdFromEventSK(sk string) (string, string) {
	// SK format: "library#<libraryId>#item#<itemId>#event#<date>"
	parts := strings.Split(sk, "#")
	if len(parts) >= 4 && parts[0] == "library" && parts[2] == "item" {
		return parts[1], parts[3]
	}
	return "", ""
}

func printConsistencyResults(r consistencyResult) {
	totalIssues := len(r.OrphanedSharedLibraries) + len(r.OrphanedItems) + len(r.OrphanedCollections) +
		len(r.OrphanedItemEvents) + len(r.ItemsWithMissingCollection) + len(r.OrphanOwners) +
		len(r.LibraryCountMismatches) + len(r.CollectionCountMismatches) + len(r.DenormalizationDrifts)

	fmt.Println("=== CONSISTENCY CHECK RESULTS ===")
	fmt.Println()

	if totalIssues == 0 {
		fmt.Println("No issues found. Data is consistent.")
		return
	}

	fmt.Printf("Total issues found: %d\n\n", totalIssues)

	// Orphaned shared libraries
	if len(r.OrphanedSharedLibraries) > 0 {
		fmt.Printf("ORPHANED SHARED LIBRARIES (%d):\n", len(r.OrphanedSharedLibraries))
		fmt.Println("  (SHARED_LIBRARY records pointing to non-existent LIBRARY)")
		for _, sl := range r.OrphanedSharedLibraries {
			fmt.Printf("  - Recipient: %s, LibraryId: %s, SourceOwner: %s\n", sl.RecipientOwnerId, sl.LibraryId, sl.SharedFromId)
		}
		fmt.Println()
	}

	// Orphaned items
	if len(r.OrphanedItems) > 0 {
		fmt.Printf("ORPHANED ITEMS (%d):\n", len(r.OrphanedItems))
		fmt.Println("  (BOOK/VIDEO records in non-existent LIBRARY)")
		for _, item := range r.OrphanedItems {
			fmt.Printf("  - Owner: %s, Library: %s, Item: %s (%s)\n", item.OwnerId, item.LibraryId, item.RecordId, item.RecordType)
		}
		fmt.Println()
	}

	// Orphaned collections
	if len(r.OrphanedCollections) > 0 {
		fmt.Printf("ORPHANED COLLECTIONS (%d):\n", len(r.OrphanedCollections))
		fmt.Println("  (COLLECTION records in non-existent LIBRARY)")
		for _, coll := range r.OrphanedCollections {
			fmt.Printf("  - Owner: %s, Library: %s, Collection: %s\n", coll.OwnerId, coll.LibraryId, coll.RecordId)
		}
		fmt.Println()
	}

	// Orphaned item events
	if len(r.OrphanedItemEvents) > 0 {
		fmt.Printf("ORPHANED ITEM EVENTS (%d):\n", len(r.OrphanedItemEvents))
		fmt.Println("  (EVENT records for non-existent ITEM)")
		for _, evt := range r.OrphanedItemEvents {
			fmt.Printf("  - Owner: %s, Library: %s, Item: %s, SK: %s\n", evt.OwnerId, evt.LibraryId, evt.ItemId, evt.EventSK)
		}
		fmt.Println()
	}

	// Items with missing collection
	if len(r.ItemsWithMissingCollection) > 0 {
		fmt.Printf("ITEMS WITH MISSING COLLECTION (%d):\n", len(r.ItemsWithMissingCollection))
		fmt.Println("  (Items referencing non-existent COLLECTION)")
		for _, item := range r.ItemsWithMissingCollection {
			fmt.Printf("  - Owner: %s, Library: %s, Item: %s, MissingCollection: %s\n", item.OwnerId, item.LibraryId, item.ItemId, item.CollectionId)
		}
		fmt.Println()
	}

	// Orphan owners
	if len(r.OrphanOwners) > 0 {
		fmt.Printf("RECORDS WITH UNKNOWN OWNER (%d):\n", len(r.OrphanOwners))
		fmt.Println("  (Records with OwnerId not in Cognito)")
		for _, o := range r.OrphanOwners {
			fmt.Printf("  - Owner: %s, Type: %s, SK: %s\n", o.OwnerId, o.EntityType, o.RecordSK)
		}
		fmt.Println()
	}

	// Library count mismatches
	if len(r.LibraryCountMismatches) > 0 {
		fmt.Printf("LIBRARY ITEM COUNT MISMATCHES (%d):\n", len(r.LibraryCountMismatches))
		fmt.Println("  (LIBRARY.TotalItems != actual item count)")
		for _, m := range r.LibraryCountMismatches {
			fmt.Printf("  - Owner: %s, Library: %s (%s), TotalItems: %d, Actual: %d\n", m.OwnerId, m.RecordId, m.RecordName, m.Expected, m.Actual)
		}
		fmt.Println()
	}

	// Collection count mismatches
	if len(r.CollectionCountMismatches) > 0 {
		fmt.Printf("COLLECTION ITEM COUNT MISMATCHES (%d):\n", len(r.CollectionCountMismatches))
		fmt.Println("  (COLLECTION.ItemCount != actual item count)")
		for _, m := range r.CollectionCountMismatches {
			fmt.Printf("  - Owner: %s, Collection: %s (%s), ItemCount: %d, Actual: %d\n", m.OwnerId, m.RecordId, m.RecordName, m.Expected, m.Actual)
		}
		fmt.Println()
	}

	// Denormalization drifts
	if len(r.DenormalizationDrifts) > 0 {
		fmt.Printf("DENORMALIZATION DRIFT (%d):\n", len(r.DenormalizationDrifts))
		fmt.Println("  (Item's denormalized field doesn't match source)")
		for _, d := range r.DenormalizationDrifts {
			fmt.Printf("  - Owner: %s, Item: %s, Field: %s, Expected: %q, Actual: %q\n", d.OwnerId, d.ItemId, d.Field, d.ExpectedVal, d.ActualVal)
		}
		fmt.Println()
	}
}
