// Generated by Claude.
package cmd

import "github.com/spf13/cobra"

var dataCmd = &cobra.Command{
	Use:   "data",
	Short: "Data integrity maintenance operations",
}

func init() {
	rootCmd.AddCommand(dataCmd)
}
