// Generated by Claude.
// Re-queues stored thumbnails through the image-processing Lambda so the lossless
// back-catalogue is re-encoded lossy. See the header comment on reencodeThumbnails.
package cmd

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	ddbtypes "github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
	"github.com/spf13/cobra"

	"alexandria.isnan.eu/cli/internal/config"
	"alexandria.isnan.eu/cli/internal/dynamodb"
	awss3 "alexandria.isnan.eu/cli/internal/s3"
)

// encodeMarkerKey is the user-metadata key the image-processing Lambda stamps onto every
// thumbnail it writes (packages/functions/images-processing/handler.js). Its PRESENCE means
// "these bytes have already been through a lossy encode"; its value records which quality.
//
// This command skips on presence rather than on a particular value, because the question it
// has to answer is "would re-encoding this degrade it", not "was it encoded at the quality we
// currently ship". Matching an exact value would make a later quality change silently turn
// this command into a generation-loss machine over the whole catalogue.
const encodeMarkerKey = "encode"

// reencodeResult holds stats for the reencode-thumbnails operation
type reencodeResult struct {
	TotalItems   int
	MissingInS3  int
	AlreadyLossy int
	Queued       int
	Failed       int
}

var reencodeDryRun bool

var dataReencodeCmd = &cobra.Command{
	Use:   "reencode-thumbnails",
	Short: "Re-encode lossless thumbnails to lossy WebP via the image processor",
	Long: `Re-queue existing thumbnails through the image-processing Lambda so that thumbnails
written before the pipeline switched to lossy WebP are re-encoded.

Thumbnails already carrying an encode marker are skipped, so the command is safe to
re-run and resumes cleanly after an interruption. Re-running it is also how you verify a
previous run: everything it queued should come back reported as already lossy.

The image processor must be deployed with the lossy setting BEFORE this is run, or every
object is re-encoded losslessly again and nothing changes.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		cfg, err := config.Load(cfgFile)
		if err != nil {
			return fmt.Errorf("loading config: %w", err)
		}
		ctx := context.Background()
		ddb, err := dynamodb.NewClient(ctx, cfg.Region, cfg.TableName)
		if err != nil {
			return fmt.Errorf("creating DynamoDB client: %w", err)
		}
		s3Client, err := awss3.NewClient(ctx, cfg.Region, cfg.BucketName)
		if err != nil {
			return fmt.Errorf("creating S3 client: %w", err)
		}
		return reencodeThumbnails(ctx, ddb, s3Client, reencodeDryRun)
	},
}

func init() {
	dataReencodeCmd.Flags().BoolVar(&reencodeDryRun, "dry-run", false, "show what would be re-encoded without making changes")
	dataCmd.AddCommand(dataReencodeCmd)
}

// reencodeThumbnails re-queues each existing thumbnail through the image-processing Lambda.
//
// It works by copying the STORED THUMBNAIL back into incoming/, not by re-fetching the item's
// PictureUrl, and that is the whole point rather than an optimisation. External sources rot:
// one sampled item's publisher URL still answers 200 but now serves a 244-byte HTML page, so
// re-fetching would have destroyed a cover we still hold perfectly. Reading only what we
// already have cannot lose an image.
//
// It is also lossless-in, lossy-out exactly once. A stored lossless thumbnail is pixel-exact to
// what sharp resized from the original, so encoding it at q85 was verified byte-identical - max
// per-pixel difference 0 - to encoding the original source directly. The resize itself is a
// no-op on the way through, since fit:inside with withoutEnlargement leaves an already-fitted
// image alone; only the encode changes.
//
// Nothing is deleted anywhere in this flow: if the Lambda fails on an object, the original
// thumbnail simply stays as it was.
func reencodeThumbnails(ctx context.Context, ddb *dynamodb.Client, s3Client *awss3.Client, dryRun bool) error {
	if dryRun {
		fmt.Println("DRY RUN MODE - no changes will be made")
	}
	fmt.Println("Scanning for thumbnails to re-encode...")
	fmt.Println()

	rows, err := ddb.Scan(ctx,
		"(EntityType = :book OR EntityType = :video) AND attribute_exists(PictureUrl)",
		nil,
		map[string]ddbtypes.AttributeValue{
			":book":  &ddbtypes.AttributeValueMemberS{Value: TypeBook},
			":video": &ddbtypes.AttributeValueMemberS{Value: TypeVideo},
		})
	if err != nil {
		return fmt.Errorf("scanning items: %w", err)
	}
	var items []itemRecord
	for _, row := range rows {
		var r itemRecord
		if err := attributevalue.UnmarshalMap(row.Attributes, &r); err != nil {
			continue // skip malformed rows, as fix-thumbnails does
		}
		items = append(items, r)
	}

	result := reencodeResult{TotalItems: len(items)}
	fmt.Printf("Found %d items with PictureUrl set\n\n", len(items))

	for i, item := range items {
		itemId := extractItemIdFromSK(item.SK)
		s3Key := thumbnailKey(item.OwnerId, item.LibraryId, itemId)

		exists, metadata, err := s3Client.HeadObjectMetadata(ctx, s3Key)
		if err != nil {
			result.Failed++
			fmt.Printf("  [%d/%d] Error checking S3 for %s: %v\n", i+1, len(items), item.Title, err)
			continue
		}

		// A missing thumbnail is `data fix-thumbnails`' problem, not this command's: there are
		// no bytes here to re-encode, and repopulating one needs the external source.
		if !exists {
			result.MissingInS3++
			continue
		}

		if marker := metadata[encodeMarkerKey]; marker != "" {
			result.AlreadyLossy++
			continue
		}

		if dryRun {
			result.Queued++
			fmt.Printf("  [%d/%d] would re-encode: %s\n", i+1, len(items), item.Title)
			continue
		}

		incomingKey := fmt.Sprintf("incoming/%s", itemId)
		if err := s3Client.CopyObject(ctx, s3Key, incomingKey,
			incomingMetadata(item.OwnerId, item.LibraryId, itemId)); err != nil {
			result.Failed++
			fmt.Printf("  [%d/%d] ERROR %s: %v\n", i+1, len(items), item.Title, err)
			continue
		}

		result.Queued++
		fmt.Printf("  [%d/%d] queued: %s\n", i+1, len(items), item.Title)
	}

	fmt.Println()
	fmt.Println("=== REENCODE THUMBNAILS RESULTS ===")
	fmt.Printf("Total items scanned:      %d\n", result.TotalItems)
	fmt.Printf("Already lossy (skipped):  %d\n", result.AlreadyLossy)
	fmt.Printf("Missing in S3 (skipped):  %d\n", result.MissingInS3)
	if dryRun {
		fmt.Printf("Would re-encode:          %d\n", result.Queued)
	} else {
		fmt.Printf("Queued for re-encoding:   %d\n", result.Queued)
	}
	fmt.Printf("Failed:                   %d\n", result.Failed)

	if !dryRun && result.Queued > 0 {
		fmt.Println()
		fmt.Println("The image processor re-encodes these asynchronously. Re-run this command to")
		fmt.Println("verify: everything queued above should then report as already lossy.")
		fmt.Println("Then invalidate the CDN, or readers keep the old bytes for up to 7 days:")
		fmt.Println("  aws cloudfront create-invalidation --paths '/thumbnails/*' \\")
		fmt.Println("    --distribution-id $(terraform -chdir=packages/infrastructure output -raw cloudfront_distribution_id)")
	}

	return nil
}
