// Generated by Claude.
// Ported from the pre-refactor packages/cli/main.go (git history, HEAD).
// Only the DynamoDB/S3 plumbing changed (now via internal/dynamodb,
// internal/s3 clients); the check logic and output text are unchanged.
package cmd

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	ddbtypes "github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
	"github.com/spf13/cobra"

	"alexandria.isnan.eu/cli/internal/config"
	"alexandria.isnan.eu/cli/internal/dynamodb"
	awss3 "alexandria.isnan.eu/cli/internal/s3"
)

// =============================================================================
// Fix Thumbnails Implementation
// =============================================================================

// itemRecord represents a DynamoDB item record for thumbnail processing
type itemRecord struct {
	PK         string  `dynamodbav:"PK"`
	SK         string  `dynamodbav:"SK"`
	EntityType string  `dynamodbav:"EntityType"`
	OwnerId    string  `dynamodbav:"OwnerId"`
	LibraryId  string  `dynamodbav:"LibraryId"`
	PictureUrl *string `dynamodbav:"PictureUrl"`
	Title      string  `dynamodbav:"Title"`
}

// thumbnailResult holds stats for the fix-thumbnails operation
type thumbnailResult struct {
	TotalItems      int
	MissingInS3     int
	Repopulated     int
	FailedToFetch   int
	SkippedNoPicUrl int
}

var thumbnailsDryRun bool

var dataThumbnailsCmd = &cobra.Command{
	Use:   "fix-thumbnails",
	Short: "Detect and repopulate missing S3 thumbnails",
	RunE: func(cmd *cobra.Command, args []string) error {
		cfg, err := config.Load(cfgFile)
		if err != nil {
			return fmt.Errorf("loading config: %w", err)
		}
		ctx := context.Background()
		ddb, err := dynamodb.NewClient(ctx, cfg.Region, cfg.TableName)
		if err != nil {
			return fmt.Errorf("creating DynamoDB client: %w", err)
		}
		s3Client, err := awss3.NewClient(ctx, cfg.Region, cfg.BucketName)
		if err != nil {
			return fmt.Errorf("creating S3 client: %w", err)
		}
		return fixThumbnails(ctx, ddb, s3Client, thumbnailsDryRun)
	},
}

func init() {
	dataThumbnailsCmd.Flags().BoolVar(&thumbnailsDryRun, "dry-run", false, "show what would be changed without making changes")
	dataCmd.AddCommand(dataThumbnailsCmd)
}

func fixThumbnails(ctx context.Context, ddb *dynamodb.Client, s3Client *awss3.Client, dryRun bool) error {
	if dryRun {
		fmt.Println("DRY RUN MODE - no changes will be made")
	}
	fmt.Println("Scanning for items with missing thumbnails...")
	fmt.Println()

	// Scan DynamoDB for all BOOK and VIDEO items with PictureUrl set.
	// Pagination and the raw AttributeValue map are handled by ddb.Scan;
	// we only need to unmarshal each row into our typed record.
	rows, err := ddb.Scan(ctx,
		"(EntityType = :book OR EntityType = :video) AND attribute_exists(PictureUrl)",
		nil,
		map[string]ddbtypes.AttributeValue{
			":book":  &ddbtypes.AttributeValueMemberS{Value: TypeBook},
			":video": &ddbtypes.AttributeValueMemberS{Value: TypeVideo},
		})
	if err != nil {
		return fmt.Errorf("scanning items: %w", err)
	}
	var items []itemRecord
	for _, row := range rows {
		var r itemRecord
		if err := attributevalue.UnmarshalMap(row.Attributes, &r); err != nil {
			continue // skip malformed rows, as the original did
		}
		items = append(items, r)
	}

	result := thumbnailResult{TotalItems: len(items)}
	fmt.Printf("Found %d items with PictureUrl set\n\n", len(items))

	for i, item := range items {
		// Check if thumbnail exists in S3
		s3Key := thumbnailKey(item.OwnerId, item.LibraryId, extractItemIdFromSK(item.SK))
		exists, err := s3Client.HeadObject(ctx, s3Key)
		if err != nil {
			fmt.Printf("  [%d/%d] Error checking S3 for %s: %v\n", i+1, len(items), item.Title, err)
			continue
		}

		if exists {
			continue // Thumbnail already exists
		}

		result.MissingInS3++

		if item.PictureUrl == nil || *item.PictureUrl == "" {
			result.SkippedNoPicUrl++
			continue
		}

		fmt.Printf("  [%d/%d] Missing thumbnail: %s\n", i+1, len(items), item.Title)
		fmt.Printf("          S3 key: %s\n", s3Key)
		fmt.Printf("          Source: %s\n", *item.PictureUrl)

		if dryRun {
			fmt.Println("          (skipped - dry run)")
			continue
		}

		// Fetch image from external URL
		imageData, contentType, err := fetchImageFromUrl(*item.PictureUrl)
		if err != nil {
			result.FailedToFetch++
			fmt.Printf("          ERROR: failed to fetch: %v\n", err)
			continue
		}

		// Upload to S3 incoming folder (image processor will handle the rest)
		itemId := extractItemIdFromSK(item.SK)
		incomingKey := fmt.Sprintf("incoming/%s", itemId)
		metadata := incomingMetadata(item.OwnerId, item.LibraryId, itemId)
		if err := s3Client.PutObject(ctx, incomingKey, imageData, contentType, metadata); err != nil {
			result.FailedToFetch++
			fmt.Printf("          ERROR: failed to upload: %v\n", err)
			continue
		}

		result.Repopulated++
		fmt.Println("          OK: uploaded to incoming/")
	}

	fmt.Println()
	fmt.Println("=== FIX THUMBNAILS RESULTS ===")
	fmt.Printf("Total items scanned:    %d\n", result.TotalItems)
	fmt.Printf("Missing in S3:          %d\n", result.MissingInS3)
	if dryRun {
		fmt.Printf("Would repopulate:       %d\n", result.MissingInS3-result.SkippedNoPicUrl)
	} else {
		fmt.Printf("Successfully uploaded:  %d\n", result.Repopulated)
		fmt.Printf("Failed to fetch/upload: %d\n", result.FailedToFetch)
	}
	fmt.Printf("Skipped (no PictureUrl):%d\n", result.SkippedNoPicUrl)

	return nil
}

// fetchImageFromUrl downloads an image from a URL
func fetchImageFromUrl(url string) ([]byte, string, error) {
	client := &http.Client{
		Timeout: 30 * time.Second,
	}

	resp, err := client.Get(url)
	if err != nil {
		return nil, "", fmt.Errorf("GET request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, "", fmt.Errorf("HTTP %d: %s", resp.StatusCode, resp.Status)
	}

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, "", fmt.Errorf("reading response body: %w", err)
	}

	contentType := resp.Header.Get("Content-Type")
	if contentType == "" {
		contentType = "application/octet-stream"
	}

	return data, contentType, nil
}

// thumbnailKey is where the image processor writes an item's finished thumbnail, and the
// path the API synthesises its CloudFront URL from (api/handlers/items.go buildItemResponse).
func thumbnailKey(ownerId, libraryId, itemId string) string {
	return fmt.Sprintf("user/%s/library/%s/item/%s", ownerId, libraryId, itemId)
}

// incomingMetadata is the instruction set the image-processing Lambda reads off an object
// dropped into incoming/: where to write the result and what to fit it inside. Shared by
// fix-thumbnails and reencode-thumbnails so the two cannot drift into disagreeing about the
// thumbnail geometry - which would be invisible until covers came back a different size.
func incomingMetadata(ownerId, libraryId, itemId string) map[string]string {
	return map[string]string{
		"targetprefix": thumbnailKey(ownerId, libraryId, itemId),
		"targetwidth":  "210",
		"targetheight": "300",
	}
}

// extractItemIdFromSK extracts item ID from SK format "library#<libraryId>#item#<itemId>"
func extractItemIdFromSK(sk string) string {
	parts := strings.Split(sk, "#")
	if len(parts) >= 4 && parts[0] == "library" && parts[2] == "item" {
		return parts[3]
	}
	return ""
}
