// Generated by Claude.
package cmd

import "testing"

func TestExtractItemIdFromSK(t *testing.T) {
	if got := extractItemIdFromSK("library#L1#item#I1"); got != "I1" {
		t.Fatalf("got %q", got)
	}
	if got := extractItemIdFromSK("library#L1#collection#C1"); got != "" {
		t.Fatalf("got %q", got)
	}
}
