// Generated by Claude.
package cmd

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"strings"
	"text/tabwriter"

	"github.com/spf13/cobra"

	ddbtypes "github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	"alexandria.isnan.eu/cli/internal/cognito"
	"alexandria.isnan.eu/cli/internal/config"
	"alexandria.isnan.eu/cli/internal/dynamodb"
	awss3 "alexandria.isnan.eu/cli/internal/s3"
)

var usersCmd = &cobra.Command{
	Use:   "users",
	Short: "Manage users",
}

var usersListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all users",
	RunE: func(cmd *cobra.Command, args []string) error {
		cfg, err := config.Load(cfgFile)
		if err != nil {
			return fmt.Errorf("loading config: %w", err)
		}
		ctx := context.Background()
		client, err := cognito.NewClient(ctx, cfg.Region, cfg.UserPoolID)
		if err != nil {
			return fmt.Errorf("creating Cognito client: %w", err)
		}
		users, err := client.ListUsers(ctx)
		if err != nil {
			return fmt.Errorf("listing users: %w", err)
		}

		w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
		fmt.Fprintln(w, "ID\tNAME\tAPPROVED\tCREATED AT")
		for _, u := range users {
			approved := "no"
			if u.Approved {
				approved = "yes"
			}
			fmt.Fprintf(w, "%s\t%s\t%s\t%s\n",
				u.ID, formatUserName(u.Name, u.Email), approved,
				u.CreatedAt.Format("2006-01-02T15:04:05Z07:00"))
		}
		return w.Flush()
	},
}

// formatUserName renders "name (email)" unless the name already IS the email.
func formatUserName(name, email string) string {
	if email != "" && email != name {
		return fmt.Sprintf("%s (%s)", name, email)
	}
	return name
}

// resolveUser loads config, builds a Cognito client, and looks up the user by
// custom:Id. Shared by approve/unapprove/delete.
func resolveUser(ctx context.Context, id string) (*config.Config, *cognito.Client, *cognito.User, error) {
	cfg, err := config.Load(cfgFile)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("loading config: %w", err)
	}
	client, err := cognito.NewClient(ctx, cfg.Region, cfg.UserPoolID)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("creating Cognito client: %w", err)
	}
	user, err := client.GetByID(ctx, id)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("checking user: %w", err)
	}
	return cfg, client, user, nil
}

var usersApproveCmd = &cobra.Command{
	Use:   "approve <user-id>",
	Short: "Approve a user (set custom:Approved = true)",
	Args:  cobra.ExactArgs(1),
	RunE:  func(cmd *cobra.Command, args []string) error { return setApproval(args[0], true) },
}

var usersUnapproveCmd = &cobra.Command{
	Use:   "unapprove <user-id>",
	Short: "Unapprove a user (set custom:Approved = false)",
	Args:  cobra.ExactArgs(1),
	RunE:  func(cmd *cobra.Command, args []string) error { return setApproval(args[0], false) },
}

func setApproval(id string, approved bool) error {
	ctx := context.Background()
	_, client, user, err := resolveUser(ctx, id)
	if err != nil {
		return err
	}
	if user == nil {
		return fmt.Errorf("unknown user: %s", id)
	}
	if err := client.SetApproval(ctx, user.Username, approved); err != nil {
		return fmt.Errorf("updating approval: %w", err)
	}
	action := "approved"
	if !approved {
		action = "unapproved"
	}
	fmt.Printf("User %s has been %s\n", user.Name, action)
	return nil
}

var deleteForce bool
var deleteDryRun bool

var usersDeleteCmd = &cobra.Command{
	Use:   "delete <user-id>",
	Short: "Delete a user and all associated data",
	Long: "Deletes all DynamoDB rows the user owns, cross-user SHARED_LIBRARY rows " +
		"pointing to the user's libraries, the user's S3 thumbnails, and the Cognito user.",
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		id := args[0]
		ctx := context.Background()

		cfg, cognitoClient, user, err := resolveUser(ctx, id)
		if err != nil {
			return err
		}
		// A missing Cognito user is not fatal: we still clean orphaned data.
		if user == nil {
			fmt.Printf("Warning: no Cognito user with id %s; cleaning data only\n", id)
		}

		ddb, err := dynamodb.NewClient(ctx, cfg.Region, cfg.TableName)
		if err != nil {
			return fmt.Errorf("creating DynamoDB client: %w", err)
		}

		owned, err := ddb.QueryByPK(ctx, "owner#"+id)
		if err != nil {
			return fmt.Errorf("querying owned rows: %w", err)
		}
		shares, err := ddb.Scan(ctx,
			"EntityType = :t AND SharedFromId = :o",
			nil,
			map[string]ddbtypes.AttributeValue{
				":t": &ddbtypes.AttributeValueMemberS{Value: TypeSharedLibrary},
				":o": &ddbtypes.AttributeValueMemberS{Value: id},
			})
		if err != nil {
			return fmt.Errorf("scanning orphan shares: %w", err)
		}

		label := id
		if user != nil {
			label = fmt.Sprintf("%s (%s)", user.Name, id)
		}
		if deleteDryRun {
			fmt.Println("[DRY RUN] The following would be deleted:")
		}
		fmt.Printf("User: %s\n", label)
		fmt.Printf("Owned DynamoDB rows: %d\n", len(owned))
		for et, n := range countByEntityType(owned) {
			fmt.Printf("  - %s: %d\n", et, n)
		}
		fmt.Printf("Cross-user shares to remove: %d\n", len(shares))
		fmt.Printf("S3 thumbnails under: user/%s/\n", id)

		if deleteDryRun {
			fmt.Println("\n[DRY RUN] No changes made.")
			return nil
		}

		if !deleteForce {
			fmt.Print("\nAre you sure you want to delete this user and all data? [y/N]: ")
			reader := bufio.NewReader(os.Stdin)
			resp, _ := reader.ReadString('\n')
			resp = strings.TrimSpace(strings.ToLower(resp))
			if resp != "y" && resp != "yes" {
				fmt.Println("Aborted.")
				return nil
			}
		}

		// Order: S3 -> DynamoDB -> Cognito, so a mid-run failure stays re-runnable
		// (the Cognito user, our lookup anchor, is removed last).
		s3Client, err := awss3.NewClient(ctx, cfg.Region, cfg.BucketName)
		if err != nil {
			return fmt.Errorf("creating S3 client: %w", err)
		}
		n, err := s3Client.DeleteByPrefix(ctx, "user/"+id+"/")
		if err != nil {
			return fmt.Errorf("deleting thumbnails: %w", err)
		}
		fmt.Printf("Deleted %d S3 objects.\n", n)

		toDelete := append(append([]dynamodb.Item{}, owned...), shares...)
		if err := ddb.DeleteItems(ctx, toDelete); err != nil {
			return fmt.Errorf("deleting DynamoDB rows: %w", err)
		}
		fmt.Printf("Deleted %d DynamoDB rows.\n", len(toDelete))

		if user != nil {
			if err := cognitoClient.DeleteUser(ctx, user.Username); err != nil {
				return fmt.Errorf("deleting Cognito user: %w", err)
			}
			fmt.Println("Deleted Cognito user.")
		}

		fmt.Printf("\nUser %s successfully deleted.\n", label)
		return nil
	},
}

// countByEntityType tallies rows by their EntityType attribute.
func countByEntityType(items []dynamodb.Item) map[string]int {
	counts := map[string]int{}
	for _, it := range items {
		et := it.EntityType
		if et == "" {
			et = "UNKNOWN"
		}
		counts[et]++
	}
	return counts
}

func init() {
	usersCmd.AddCommand(usersListCmd)
	usersCmd.AddCommand(usersApproveCmd)
	usersCmd.AddCommand(usersUnapproveCmd)
	usersDeleteCmd.Flags().BoolVarP(&deleteForce, "force", "f", false, "skip confirmation prompt")
	usersDeleteCmd.Flags().BoolVar(&deleteDryRun, "dry-run", false, "show what would be deleted without making changes")
	usersCmd.AddCommand(usersDeleteCmd)
	rootCmd.AddCommand(usersCmd)
}
