// Generated by Claude.
import { createContext, useContext, useState, useEffect, useCallback } from 'react';
import { signIn as cognitoSignIn, signOut as cognitoSignOut, fetchAuthSession } from 'aws-amplify/auth';

const AuthContext = createContext(null);

// Cognito 'sub' claim → remove dashes and uppercase
const extractUserId = (idToken) =>
  idToken.payload.sub.replaceAll('-', '').toUpperCase();

export const AuthProvider = ({ children }) => {
  const [user, setUser] = useState(null);
  const [isLoading, setIsLoading] = useState(true);

  // Check for an existing session on mount
  useEffect(() => {
    const checkSession = async () => {
      try {
        const session = await fetchAuthSession();
        if (session?.tokens) {
          setUser({
            id: extractUserId(session.tokens.idToken),
            token: session.tokens.idToken.toString(),
          });
        }
      } catch {
        // No active session — stay unauthenticated
      } finally {
        setIsLoading(false);
      }
    };
    checkSession();
  }, []);

  const signIn = useCallback(async (username, password) => {
    try {
      await cognitoSignIn({ username, password });
    } catch (err) {
      // Already logged in — proceed to fetch current session
      if (err.name !== 'UserAlreadyAuthenticatedException') throw err;
    }
    const session = await fetchAuthSession();
    setUser({
            id: extractUserId(session.tokens.idToken),
            token: session.tokens.idToken.toString(),
          });
  }, []);

  const signOut = useCallback(async () => {
    await cognitoSignOut();
    setUser(null);
  }, []);

  return (
    <AuthContext.Provider
      value={{
        user,
        isAuthenticated: !!user,
        isLoading,
        signIn,
        signOut,
      }}
    >
      {children}
    </AuthContext.Provider>
  );
};

export const useAuth = () => {
  const ctx = useContext(AuthContext);
  if (!ctx) throw new Error('useAuth must be used within AuthProvider');
  return ctx;
};
