import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import { VitePWA } from 'vite-plugin-pwa';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';
import { mockApi } from './tools/vite-plugin-mock-api.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const gitCommitHash = () => {
  try {
    return execSync('git rev-parse --short HEAD').toString().trim();
  } catch {
    return 'unknown';
  }
};

// output.json is generated by `make infra-output` and gitignored. Fall back to empty values
// rather than failing the build: mock mode and CI must work without Terraform or AWS.
const loadOutput = () => {
  const file = path.resolve(__dirname, 'output.json');
  if (!fs.existsSync(file)) {
    return { alexandriaUserPoolId: '', alexandriaClientId: '', apiEndpoint: '' };
  }
  return JSON.parse(fs.readFileSync(file, 'utf8'));
};

export default defineConfig(({ command }) => {
  const output = loadOutput();
  const isMock = process.env.VITE_MOCK === '1';

  // A production bundle with no pool id cannot authenticate anyone, and the failure only
  // surfaces when a reader submits the login form. `frontend-v3-build` runs `infra-output`
  // first, so empty config at build time means that step failed — fail here rather than ship
  // it. Dev and mock builds are exempt: dev shows the same message in the page (main.jsx),
  // and mock mode never reaches Cognito.
  if (command === 'build' && !isMock && (!output.alexandriaUserPoolId || !output.alexandriaClientId)) {
    throw new Error(
      'Refusing to build: packages/web-client-v3/output.json has no Cognito user pool id or ' +
        'client id, so the bundle could not authenticate anyone.\n' +
        '  aws sso login && make infra-output\n' +
        'Or build the fixture-backed app with VITE_MOCK=1.',
    );
  }

  return {
    define: {
      __APP_CONFIG__: JSON.stringify({
        userPoolId: output.alexandriaUserPoolId,
        clientId: output.alexandriaClientId,
      }),
      __BUILD_HASH__: JSON.stringify(gitCommitHash()),
      __MOCK__: JSON.stringify(isMock),
    },
    server: {
      port: 5173,
      // Fail loudly instead of drifting to another port: the OAuth callback URL is fixed.
      // v2 also uses 5173, so only one dev server runs at a time — a deliberate trade for
      // Google sign-in working locally with no Terraform change.
      strictPort: true,
      proxy:
        isMock || !output.apiEndpoint
          ? undefined
          : { '/api': { target: output.apiEndpoint, changeOrigin: true, secure: true } },
    },
    preview: { port: 5173, strictPort: true },
    plugins: [
      react(),
      tailwindcss(),
      VitePWA({ registerType: 'prompt' }),
      ...(isMock ? [mockApi()] : []),
    ],
    resolve: { alias: { '@': path.resolve(__dirname, './src') } },
    build: {
      rollupOptions: {
        output: {
          manualChunks: {
            amplify: ['aws-amplify'],
            react: ['react', 'react-dom', 'react-router-dom'],
            // Its own chunk, never merged into the entry bundle: most sessions are lookups, not
            // cataloguing sessions, so the barcode decoder must not cost every reader who never
            // opens the camera a single byte of it.
            zxing: ['@zxing/browser', '@zxing/library'],
          },
        },
      },
    },
  };
});
