import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import { VitePWA } from 'vite-plugin-pwa';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';
import { mockApi } from './tools/vite-plugin-mock-api.js';
// The icon set is declared once in tools/pwa-icons.js and read here, by scripts/generate-icons.mjs
// and by scripts/check-browser.mjs. A manifest holding its own hand-typed copy of the list is how
// it comes to advertise a file nobody generates.
import { MANIFEST_ICONS } from './tools/pwa-icons.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// package.json's own version, read at build time. About prints it beside the commit hash so a
// reader can tell an administrator which build they are on; nothing here invents a value.
const appVersion = () =>
  JSON.parse(fs.readFileSync(path.resolve(__dirname, 'package.json'), 'utf8')).version;

const gitCommitHash = () => {
  try {
    return execSync('git rev-parse --short HEAD').toString().trim();
  } catch {
    return 'unknown';
  }
};

// output.json is generated by `make infra-output` and gitignored. Fall back to empty values
// rather than failing the build: mock mode and CI must work without Terraform or AWS.
const loadOutput = () => {
  const file = path.resolve(__dirname, 'output.json');
  if (!fs.existsSync(file)) {
    return { alexandriaUserPoolId: '', alexandriaClientId: '', apiEndpoint: '' };
  }
  return JSON.parse(fs.readFileSync(file, 'utf8'));
};

export default defineConfig(({ command }) => {
  const output = loadOutput();
  const isMock = process.env.VITE_MOCK === '1';

  // A production bundle with no pool id cannot authenticate anyone, and the failure only
  // surfaces when a reader submits the login form. `frontend-v3-build` runs `infra-output`
  // first, so empty config at build time means that step failed — fail here rather than ship
  // it. Dev and mock builds are exempt: dev shows the same message in the page (main.jsx),
  // and mock mode never reaches Cognito.
  if (command === 'build' && !isMock && (!output.alexandriaUserPoolId || !output.alexandriaClientId)) {
    throw new Error(
      'Refusing to build: packages/web-client-v3/output.json has no Cognito user pool id or ' +
        'client id, so the bundle could not authenticate anyone.\n' +
        '  aws sso login && make infra-output\n' +
        'Or build the fixture-backed app with VITE_MOCK=1.',
    );
  }

  return {
    define: {
      __APP_CONFIG__: JSON.stringify({
        userPoolId: output.alexandriaUserPoolId,
        clientId: output.alexandriaClientId,
      }),
      __BUILD_HASH__: JSON.stringify(gitCommitHash()),
      __APP_VERSION__: JSON.stringify(appVersion()),
      __MOCK__: JSON.stringify(isMock),
    },
    server: {
      port: 5173,
      // Fail loudly instead of drifting to another port: the OAuth callback URL is fixed.
      // v2 also uses 5173, so only one dev server runs at a time — a deliberate trade for
      // Google sign-in working locally with no Terraform change.
      strictPort: true,
      proxy:
        isMock || !output.apiEndpoint
          ? undefined
          : { '/api': { target: output.apiEndpoint, changeOrigin: true, secure: true } },
    },
    preview: { port: 5173, strictPort: true },
    plugins: [
      react(),
      tailwindcss(),
      VitePWA({
        // 'prompt', not 'autoUpdate': a silent swap can replace the bundle under a reader who is
        // mid-capture. src/pwa/UpdatePrompt.jsx is what turns the waiting worker into an offer —
        // without it a new build installs and waits forever, which is the whole reason that
        // component shipped ahead of this task.
        registerType: 'prompt',
        manifest: {
          name: 'Alexandria',
          // 'Alexandria' fits a home-screen label at 12 characters, so there is nothing to
          // shorten; a different short_name would only give the same app two names.
          short_name: 'Alexandria',
          description: 'A circulation record for a physical collection',
          lang: 'en',
          // DESIGN.md §2: the ink ground the icon and the item-detail cover are built on, and the
          // paper the app itself sits on. theme_color paints the platform's own chrome, so it
          // matches the <meta name="theme-color"> in index.html; background_color is what a cold
          // launch shows before the first paint, so it matches --paper rather than the icon.
          theme_color: '#0B0B0B',
          background_color: '#F6F6F3',
          display: 'standalone',
          // NO `orientation` LOCK, deliberately, and the plan asked for `'portrait'`.
          //
          // PRODUCT.md is phone-first and says so — but it also requires that "tablet and desktop
          // must be sane and usable", and a manifest lock does not express a preference: on an
          // installed Android app it HARD-LOCKS rotation, so a tablet held in landscape cannot
          // display the app at all. That trades a real capability for a preference already
          // satisfied by the layout.
          //
          // Two other things in this build assume landscape is reachable. DESIGN.md §4 provides
          // for it explicitly — the 448px column exists so a wide viewport is not a stretched
          // phone — and the film capture screen's no-scroll ruling was MEASURED at 667x390 and
          // records "in landscape the page scrolls" as an accepted consequence. A lock would make
          // that state unreachable on one platform and leave the reasoning stranded.
          //
          // "Nothing has a landscape layout to rotate into" is the argument for not BUILDING one.
          // It is not an argument for preventing rotation, which is a different act.
          // '/' rather than '/libraries': routes.jsx sends an unknown path to /libraries anyway,
          // and starting at the root keeps the launch going through the same auth resolution a
          // cold browser load does.
          start_url: '/',
          scope: '/',
          icons: MANIFEST_ICONS,
        },
        workbox: {
          // Beyond the js/css/html default: the fonts and the icons. The fonts are the identity
          // (DESIGN.md §3) and a missing woff2 falls back silently to system-ui, which is exactly
          // the failure that hid for three slices; the icons are what an installed app is, and an
          // icon fetched over a dead connection is a blank home-screen tile.
          globPatterns: ['**/*.{js,css,html,ico,png,svg,woff2}'],
        },
      }),
      ...(isMock ? [mockApi()] : []),
    ],
    resolve: { alias: { '@': path.resolve(__dirname, './src') } },
    build: {
      rollupOptions: {
        output: {
          manualChunks: {
            amplify: ['aws-amplify'],
            react: ['react', 'react-dom', 'react-router-dom'],
            // Its own chunk, never merged into the entry bundle: most sessions are lookups, not
            // cataloguing sessions, so the barcode decoder must not cost every reader who never
            // opens the camera a single byte of it.
            zxing: ['@zxing/browser', '@zxing/library'],
            // There was a `webcam: ['react-webcam']` chunk here on the same reasoning. The
            // dependency is gone: it owned its own MediaStream and could not be handed one,
            // which was the only thing preventing the camera from surviving the cataloguing
            // loop. The cover capture is now a plain <video> plus the shared lease, so there is
            // no third-party weight left on that route to isolate.
          },
        },
      },
    },
  };
});
