import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import { VitePWA } from 'vite-plugin-pwa';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const gitCommitHash = () => {
  try {
    return execSync('git rev-parse --short HEAD').toString().trim();
  } catch {
    return 'unknown';
  }
};

// output.json is generated by `make infra-output` and gitignored. Fall back to empty values
// rather than failing the build: mock mode and CI must work without Terraform or AWS.
const loadOutput = () => {
  const file = path.resolve(__dirname, 'output.json');
  if (!fs.existsSync(file)) {
    return { alexandriaUserPoolId: '', alexandriaClientId: '', apiEndpoint: '' };
  }
  return JSON.parse(fs.readFileSync(file, 'utf8'));
};

export default defineConfig(() => {
  const output = loadOutput();
  const isMock = process.env.VITE_MOCK === '1';

  return {
    define: {
      __APP_CONFIG__: JSON.stringify({
        userPoolId: output.alexandriaUserPoolId,
        clientId: output.alexandriaClientId,
      }),
      __BUILD_HASH__: JSON.stringify(gitCommitHash()),
      __MOCK__: JSON.stringify(isMock),
    },
    server: {
      port: 5173,
      // Fail loudly instead of drifting to another port: the OAuth callback URL is fixed.
      // v2 also uses 5173, so only one dev server runs at a time — a deliberate trade for
      // Google sign-in working locally with no Terraform change.
      strictPort: true,
      proxy:
        isMock || !output.apiEndpoint
          ? undefined
          : { '/api': { target: output.apiEndpoint, changeOrigin: true, secure: true } },
    },
    preview: { port: 5173, strictPort: true },
    plugins: [react(), tailwindcss(), VitePWA({ registerType: 'prompt' })],
    resolve: { alias: { '@': path.resolve(__dirname, './src') } },
    build: {
      rollupOptions: {
        output: {
          manualChunks: {
            amplify: ['aws-amplify'],
            react: ['react', 'react-dom', 'react-router-dom'],
          },
        },
      },
    },
  };
});
