const FETCHING_TOKEN = 'FETCHING_TOKEN';
const FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS';
const FETCH_TOKEN_ERROR = 'FETCH_TOKEN_ERROR';
const SIGNING_IN = 'SIGNING_IN';
const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';

const SIGNING_OUT = 'SIGNING_OUT';
const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';

const READING_APP_PREFERENCES = 'READING_APP_PREFERENCES';
const READ_APP_PREFERENCES_SUCCESS = 'READ_APP_PREFERENCES_SUCCESS';
const READ_APP_PREFERENCES_ERROR = 'READ_APP_PREFERENCES_ERROR';

const WRITING_APP_PREFERENCES = 'WRITING_APP_PREFERENCES';
const WRITE_APP_PREFERENCES_SUCCESS = 'WRITE_APP_PREFERENCES_SUCCESS';
const WRITE_APP_PREFERENCES_ERROR = 'WRITE_APP_PREFERENCES_ERROR';

export default {
  FETCHING_TOKEN,
  FETCH_TOKEN_SUCCESS,
  FETCH_TOKEN_ERROR,
  SIGNING_IN,
  SIGN_IN_SUCCESS,
  SIGN_IN_ERROR,
  DISMISS_NOTIFICATION,
  SIGNING_OUT,
  SIGN_OUT_SUCCESS,
  SIGN_OUT_ERROR,
  READING_APP_PREFERENCES,
  READ_APP_PREFERENCES_SUCCESS,
  READ_APP_PREFERENCES_ERROR,
  WRITING_APP_PREFERENCES,
  WRITE_APP_PREFERENCES_SUCCESS,
  WRITE_APP_PREFERENCES_ERROR,
};
