const APP_WAITING = 'APP_WAITING';
const APP_ERROR = 'APP_ERROR';
const APP_REFRESHING = 'APP_REFRESHING';

const FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS';
const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';
const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
const READ_APP_PREFERENCES_SUCCESS = 'READ_APP_PREFERENCES_SUCCESS';
const WRITE_APP_PREFERENCES_SUCCESS = 'WRITE_APP_PREFERENCES_SUCCESS';
const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';

const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const DETECT_BOOK_SUCCESS = 'DETECT_BOOK_SUCCESS';
const FETCH_LIBRARIES_SUCCESS = 'FETCH_LIBRARIES_SUCCESS';
const CREATE_LIBRARY_SUCCESS = 'CREATE_LIBRARY_SUCCESS';
const UPDATE_LIBRARY_SUCCESS = 'UPDATE_LIBRARY_SUCCESS';
const DELETE_LIBRARY_SUCCESS = 'DELETE_LIBRARY_SUCCESS';

const FETCH_LIBRARY_ITEMS_SUCCESS = 'FETCH_LIBRARY_ITEMS_SUCCESS';
const REFRESH_LIBRARY_ITEMS_SUCCESS = 'REFRESH_LIBRARY_ITEMS_SUCCESS';
const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
const DELETE_LIBRARY_ITEM_SUCCESS = 'DELETE_LIBRARY_ITEM_SUCCESS';
const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';

const RESET_LIBRARY_ITEMS = 'RESET_LIBRARY_ITEMS';

const SEARCH_ITEMS_SUCCESS = 'SEARCH_ITEMS_SUCCESS';

const SHARE_LIBRARY_SUCCESS = 'SHARE_LIBRARY_SUCCESS';
const UNSHARE_LIBRARY_SUCCESS = 'UNSHARE_LIBRARY_SUCCESS';

const LEND_ITEM_SUCCESS = 'LEND_ITEM_SUCCESS';
const RETURN_ITEM_SUCCESS = 'RETURN_ITEM_SUCCESS';
const FETCH_ITEM_HISTORY_SUCCESS = 'FETCH_ITEM_HISTORY_SUCCESS';
const REFRESH_ITEM_HISTORY_SUCCESS = 'REFRESH_ITEM_HISTORY_SUCCESS';

export default {
  REFRESH_ITEM_HISTORY_SUCCESS,
  FETCH_ITEM_HISTORY_SUCCESS,
  RETURN_ITEM_SUCCESS,
  LEND_ITEM_SUCCESS,
  UNSHARE_LIBRARY_SUCCESS,
  SHARE_LIBRARY_SUCCESS,
  CHANGE_PASSWORD_SUCCESS,
  SEARCH_ITEMS_SUCCESS,
  RESET_LIBRARY_ITEMS,
  UPDATE_BOOK_SUCCESS,
  DELETE_LIBRARY_ITEM_SUCCESS,
  REFRESH_LIBRARY_ITEMS_SUCCESS,
  CREATE_BOOK_SUCCESS,
  FETCH_LIBRARY_ITEMS_SUCCESS,
  DELETE_LIBRARY_SUCCESS,
  FETCH_TOKEN_SUCCESS,
  SIGN_IN_SUCCESS,
  DISMISS_NOTIFICATION,
  SIGN_OUT_SUCCESS,
  SIGNUP_SUCCESS,
  READ_APP_PREFERENCES_SUCCESS,
  WRITE_APP_PREFERENCES_SUCCESS,
  DETECT_BOOK_SUCCESS,
  FETCH_LIBRARIES_SUCCESS,
  CREATE_LIBRARY_SUCCESS,
  UPDATE_LIBRARY_SUCCESS,
  APP_WAITING,
  APP_ERROR,
  APP_REFRESHING,
};
