const APP_WAITING = 'APP_WAITING';
const APP_ERROR = 'APP_ERROR';

const FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS';
const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';
const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
const READ_APP_PREFERENCES_SUCCESS = 'READ_APP_PREFERENCES_SUCCESS';
const WRITE_APP_PREFERENCES_SUCCESS = 'WRITE_APP_PREFERENCES_SUCCESS';

const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const DETECT_BOOK_SUCCESS = 'DETECT_BOOK_SUCCESS';
const FETCH_LIBRARIES_SUCCESS = 'FETCH_LIBRARIES_SUCCESS';
const CREATE_LIBRARY_SUCCESS = 'CREATE_LIBRARY_SUCCESS';
const UPDATE_LIBRARY_SUCCESS = 'UPDATE_LIBRARY_SUCCESS';
const DELETE_LIBRARY_SUCCESS = 'DELETE_LIBRARY_SUCCESS';

const FETCH_LIBRARY_ITEMS_SUCCESS = 'FETCH_LIBRARY_ITEMS_SUCCESS';

const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';

export default {
  CREATE_BOOK_SUCCESS,
  FETCH_LIBRARY_ITEMS_SUCCESS,
  DELETE_LIBRARY_SUCCESS,
  FETCH_TOKEN_SUCCESS,
  SIGN_IN_SUCCESS,
  DISMISS_NOTIFICATION,
  SIGN_OUT_SUCCESS,
  SIGNUP_SUCCESS,
  READ_APP_PREFERENCES_SUCCESS,
  WRITE_APP_PREFERENCES_SUCCESS,
  DETECT_BOOK_SUCCESS,
  FETCH_LIBRARIES_SUCCESS,
  CREATE_LIBRARY_SUCCESS,
  UPDATE_LIBRARY_SUCCESS,
  APP_WAITING,
  APP_ERROR,
};
