// Generated by Claude.
// Reusable Timeline component with left-aligned vertical layout
// Supports custom dot colors and flexible content rendering
import { cn } from '@/lib/utils';

// Predefined color variants for dots
const dotVariants = {
  default: 'bg-primary border-primary',
  orange: 'bg-orange-500 border-orange-500',
  green: 'bg-green-500 border-green-500',
  red: 'bg-red-500 border-red-500',
  blue: 'bg-blue-500 border-blue-500',
  muted: 'bg-muted-foreground border-muted-foreground',
};

// Individual timeline item
const TimelineItem = ({ children, dotColor = 'default', isLast = false, className }) => {
  const dotClass = dotVariants[dotColor] || dotVariants.default;

  return (
    <div className={cn('relative flex gap-4', className)}>
      {/* Timeline line + dot */}
      <div className="flex flex-col items-center">
        {/* Dot */}
        <div className={cn('shrink-0 h-3 w-3 rounded-full border-2', dotClass)} />
        {/* Connector line */}
        {!isLast && <div className="w-0.5 flex-1 bg-border" />}
      </div>

      {/* Content */}
      <div className="flex-1 pb-6">{children}</div>
    </div>
  );
};

// Timeline container
const Timeline = ({ children, className }) => {
  return (
    <div className={cn('relative', className)}>
      {children}
    </div>
  );
};

// Attach Item as a static property for compound component pattern
Timeline.Item = TimelineItem;

export { Timeline, TimelineItem };
export default Timeline;
