// Generated by Claude.
// S3 client for thumbnail lifecycle operations.
package s3

import (
	"bytes"
	"context"
	"fmt"
	"net/url"
	"strings"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/s3/types"
)

type Client struct {
	client *s3.Client
	bucket string
}

func NewClient(ctx context.Context, region, bucket string) (*Client, error) {
	cfg, err := config.LoadDefaultConfig(ctx, config.WithRegion(region))
	if err != nil {
		return nil, fmt.Errorf("loading AWS config: %w", err)
	}
	return &Client{
		client: s3.NewFromConfig(cfg),
		bucket: bucket,
	}, nil
}

// DeleteByPrefix removes every object under prefix, returning the count deleted.
func (c *Client) DeleteByPrefix(ctx context.Context, prefix string) (int, error) {
	deleted := 0
	var token *string
	for {
		list, err := c.client.ListObjectsV2(ctx, &s3.ListObjectsV2Input{
			Bucket:            aws.String(c.bucket),
			Prefix:            aws.String(prefix),
			ContinuationToken: token,
		})
		if err != nil {
			return deleted, fmt.Errorf("listing objects: %w", err)
		}
		if len(list.Contents) > 0 {
			var objs []types.ObjectIdentifier
			for _, o := range list.Contents {
				objs = append(objs, types.ObjectIdentifier{Key: o.Key})
			}
			out, err := c.client.DeleteObjects(ctx, &s3.DeleteObjectsInput{
				Bucket: aws.String(c.bucket),
				Delete: &types.Delete{Objects: objs, Quiet: aws.Bool(true)},
			})
			if err != nil {
				return deleted, fmt.Errorf("deleting objects: %w", err)
			}
			// With Quiet=true, S3 omits the per-key success list but still returns
			// an Errors entry for every key it failed to delete without surfacing a
			// call-level error. Surface those so a partial failure isn't silently
			// counted as a full wipe (the delete cascade must leave nothing behind).
			if len(out.Errors) > 0 {
				first := out.Errors[0]
				return deleted + len(objs) - len(out.Errors),
					fmt.Errorf("failed to delete %d object(s) under %q (e.g. %s: %s)",
						len(out.Errors), prefix, aws.ToString(first.Key), aws.ToString(first.Message))
			}
			deleted += len(objs)
		}
		if aws.ToBool(list.IsTruncated) {
			token = list.NextContinuationToken
			continue
		}
		break
	}
	return deleted, nil
}

// isNotFound reports whether a HEAD error means "the object is not there" rather than
// "the request failed". Extracted from HeadObject so that the two head paths classify an
// error identically: a missing object and an expired token must never be conflated, since
// callers act on absence (re-fetch, re-queue) and would act on a credentials failure the
// same way if it were reported as absence.
func isNotFound(err error) bool {
	e := err.Error()
	return strings.Contains(e, "NotFound") || strings.Contains(e, "NoSuchKey") ||
		strings.Contains(e, "404") || strings.Contains(e, "not found")
}

// HeadObject reports whether key exists.
func (c *Client) HeadObject(ctx context.Context, key string) (bool, error) {
	exists, _, err := c.HeadObjectMetadata(ctx, key)
	return exists, err
}

// HeadObjectMetadata reports whether key exists and returns its user metadata.
// S3 lowercases user-metadata keys in flight, so a value written as `Metadata: { encode }`
// reads back under "encode" here and as `metadata.encode` in the image-processing Lambda.
func (c *Client) HeadObjectMetadata(ctx context.Context, key string) (bool, map[string]string, error) {
	out, err := c.client.HeadObject(ctx, &s3.HeadObjectInput{
		Bucket: aws.String(c.bucket),
		Key:    aws.String(key),
	})
	if err != nil {
		if isNotFound(err) {
			return false, nil, nil
		}
		return false, nil, err
	}
	return true, out.Metadata, nil
}

// copySource builds the `bucket/key` value CopyObject expects, escaping each path segment
// while leaving the separators intact. Escaping the whole string would encode the slashes
// themselves and address one object whose name contains "/" rather than a nested key.
func copySource(bucket, key string) string {
	parts := strings.Split(key, "/")
	for i, p := range parts {
		parts[i] = url.PathEscape(p)
	}
	return url.PathEscape(bucket) + "/" + strings.Join(parts, "/")
}

// CopyObject copies srcKey onto dstKey inside the same bucket, replacing the object's user
// metadata with the supplied map rather than carrying the source's across.
//
// This is a server-side copy: the bytes never travel to the caller, which is what makes
// re-queueing the whole back-catalogue of thumbnails through the image-processing Lambda
// cheap - the CLI moves keys, not images.
func (c *Client) CopyObject(ctx context.Context, srcKey, dstKey string, metadata map[string]string) error {
	_, err := c.client.CopyObject(ctx, &s3.CopyObjectInput{
		Bucket:            aws.String(c.bucket),
		Key:               aws.String(dstKey),
		CopySource:        aws.String(copySource(c.bucket, srcKey)),
		Metadata:          metadata,
		MetadataDirective: types.MetadataDirectiveReplace,
	})
	if err != nil {
		return fmt.Errorf("copying %s to %s: %w", srcKey, dstKey, err)
	}
	return nil
}

// PutObject uploads data with content type and metadata.
func (c *Client) PutObject(ctx context.Context, key string, data []byte, contentType string, metadata map[string]string) error {
	_, err := c.client.PutObject(ctx, &s3.PutObjectInput{
		Bucket:      aws.String(c.bucket),
		Key:         aws.String(key),
		Body:        bytes.NewReader(data),
		ContentType: aws.String(contentType),
		Metadata:    metadata,
	})
	return err
}
