// Generated by Claude.
// S3 client for thumbnail lifecycle operations.
package s3

import (
	"bytes"
	"context"
	"fmt"
	"strings"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/s3/types"
)

type Client struct {
	client *s3.Client
	bucket string
}

func NewClient(ctx context.Context, region, bucket string) (*Client, error) {
	cfg, err := config.LoadDefaultConfig(ctx, config.WithRegion(region))
	if err != nil {
		return nil, fmt.Errorf("loading AWS config: %w", err)
	}
	return &Client{
		client: s3.NewFromConfig(cfg),
		bucket: bucket,
	}, nil
}

// DeleteByPrefix removes every object under prefix, returning the count deleted.
func (c *Client) DeleteByPrefix(ctx context.Context, prefix string) (int, error) {
	deleted := 0
	var token *string
	for {
		list, err := c.client.ListObjectsV2(ctx, &s3.ListObjectsV2Input{
			Bucket:            aws.String(c.bucket),
			Prefix:            aws.String(prefix),
			ContinuationToken: token,
		})
		if err != nil {
			return deleted, fmt.Errorf("listing objects: %w", err)
		}
		if len(list.Contents) > 0 {
			var objs []types.ObjectIdentifier
			for _, o := range list.Contents {
				objs = append(objs, types.ObjectIdentifier{Key: o.Key})
			}
			out, err := c.client.DeleteObjects(ctx, &s3.DeleteObjectsInput{
				Bucket: aws.String(c.bucket),
				Delete: &types.Delete{Objects: objs, Quiet: aws.Bool(true)},
			})
			if err != nil {
				return deleted, fmt.Errorf("deleting objects: %w", err)
			}
			// With Quiet=true, S3 omits the per-key success list but still returns
			// an Errors entry for every key it failed to delete without surfacing a
			// call-level error. Surface those so a partial failure isn't silently
			// counted as a full wipe (the delete cascade must leave nothing behind).
			if len(out.Errors) > 0 {
				first := out.Errors[0]
				return deleted + len(objs) - len(out.Errors),
					fmt.Errorf("failed to delete %d object(s) under %q (e.g. %s: %s)",
						len(out.Errors), prefix, aws.ToString(first.Key), aws.ToString(first.Message))
			}
			deleted += len(objs)
		}
		if aws.ToBool(list.IsTruncated) {
			token = list.NextContinuationToken
			continue
		}
		break
	}
	return deleted, nil
}

// HeadObject reports whether key exists.
func (c *Client) HeadObject(ctx context.Context, key string) (bool, error) {
	_, err := c.client.HeadObject(ctx, &s3.HeadObjectInput{
		Bucket: aws.String(c.bucket),
		Key:    aws.String(key),
	})
	if err != nil {
		e := err.Error()
		if strings.Contains(e, "NotFound") || strings.Contains(e, "NoSuchKey") ||
			strings.Contains(e, "404") || strings.Contains(e, "not found") {
			return false, nil
		}
		return false, err
	}
	return true, nil
}

// PutObject uploads data with content type and metadata.
func (c *Client) PutObject(ctx context.Context, key string, data []byte, contentType string, metadata map[string]string) error {
	_, err := c.client.PutObject(ctx, &s3.PutObjectInput{
		Bucket:      aws.String(c.bucket),
		Key:         aws.String(key),
		Body:        bytes.NewReader(data),
		ContentType: aws.String(contentType),
		Metadata:    metadata,
	})
	return err
}
