// Generated by Claude.
package s3

import (
	"errors"
	"testing"
)

func TestCopySourceKeepsSeparatorsAndEscapesSegments(t *testing.T) {
	// Hand-derived rather than taken from the implementation: CopyObject wants
	// "bucket/key" with each segment percent-encoded and the slashes left alone.
	// Escaping the whole string would send "bucket%2Fuser%2F..." and address one
	// object literally named with slashes in it.
	if got, want := copySource("alexandria-items", "user/ABC/library/DEF/item/GHI"),
		"alexandria-items/user/ABC/library/DEF/item/GHI"; got != want {
		t.Errorf("copySource() = %q, want %q", got, want)
	}

	// A segment needing escaping must be escaped, and only that segment.
	if got, want := copySource("bucket", "user/a b/item/c+d"),
		"bucket/user/a%20b/item/c+d"; got != want {
		t.Errorf("copySource() with unsafe chars = %q, want %q", got, want)
	}
}

func TestIsNotFoundSeparatesAbsenceFromFailure(t *testing.T) {
	// Absence: the caller is entitled to act on it (re-queue, re-fetch).
	for _, msg := range []string{
		"operation error S3: HeadObject, https response error StatusCode: 404, api error NotFound: Not Found",
		"NoSuchKey: The specified key does not exist.",
		"api error 404: not found",
	} {
		if !isNotFound(errors.New(msg)) {
			t.Errorf("isNotFound(%q) = false, want true", msg)
		}
	}

	// Failure: must NOT read as absence, or an expired token makes every thumbnail
	// look missing and the caller happily "repairs" the entire catalogue.
	for _, msg := range []string{
		"operation error S3: HeadObject, https response error StatusCode: 403, api error Forbidden",
		"Error when retrieving token from sso: Token has expired and refresh failed",
		"dial tcp: lookup s3.eu-central-1.amazonaws.com: no such host",
	} {
		if isNotFound(errors.New(msg)) {
			t.Errorf("isNotFound(%q) = true, want false", msg)
		}
	}
}
