// Generated by Claude.
// API client with auth token injection
import { fetchAuthSession } from 'aws-amplify/auth';
import { config } from '@/config';

const BASE_URL = `${config.apiBaseUrl}/v1`;

// Fetches current JWT token from Cognito session
const getAuthToken = async () => {
  const session = await fetchAuthSession();
  return session?.tokens?.idToken?.toString();
};

// Base fetch wrapper with auth and error handling
export const apiClient = async (endpoint, options = {}) => {
  const token = await getAuthToken();

  const headers = {
    'Content-Type': 'application/json',
    ...options.headers,
  };

  if (token) {
    headers['Authorization'] = `Bearer ${token}`;
  }

  const response = await fetch(`${BASE_URL}${endpoint}`, {
    ...options,
    headers,
  });

  // No content response
  if (response.status === 204 || response.headers.get('content-length') === '0') {
    return null;
  }

  const data = await response.json();

  if (!response.ok) {
    const error = new Error(data.message || 'API request failed');
    error.status = response.status;
    error.data = data;
    // Flag for pending approval (403 with specific message)
    error.isPendingApproval = response.status === 403 && data.message === 'Pending approval';
    throw error;
  }

  return data;
};

// Convenience methods
export const api = {
  get: (endpoint) => apiClient(endpoint, { method: 'GET' }),
  post: (endpoint, body) => apiClient(endpoint, { method: 'POST', body: JSON.stringify(body) }),
  put: (endpoint, body) => apiClient(endpoint, { method: 'PUT', body: JSON.stringify(body) }),
  delete: (endpoint) => apiClient(endpoint, { method: 'DELETE' }),
};
