// Generated by Claude.
// Detection API endpoints - ISBN lookup
import { api } from './client';

export const detectionApi = {
  // Detect book by ISBN code
  // type: 0 = Book
  detectBook: (isbn) => api.post('/detections', { type: 0, code: isbn }),
};
