// Generated by Claude.
// Library API endpoints
import { api } from './client';

export const librariesApi = {
  // Get all libraries (owned + shared)
  getAll: () => api.get('/libraries'),

  // Create a new library
  create: (data) => api.post('/libraries', data),

  // Update a library
  update: (libraryId, data) => api.put(`/libraries/${libraryId}`, data),

  // Delete a library
  delete: (libraryId) => api.delete(`/libraries/${libraryId}`),

  // Share a library with another user
  share: (libraryId, userName) => api.post(`/libraries/${libraryId}/share`, { userName }),

  // Unshare a library from one or more users
  unshare: (libraryId, userNames) => api.post(`/libraries/${libraryId}/unshare`, { userNames }),

  // Get items in a library with cursor-based pagination
  getItems: (libraryId, { limit = 20, nextToken } = {}) => {
    const params = new URLSearchParams({ limit: String(limit) });
    if (nextToken) params.append('nextToken', nextToken);
    return api.get(`/libraries/${libraryId}/items?${params}`);
  },
};
