// Generated by Claude.
// Search API client - fuzzy search across all user's libraries
import { api } from './client';

export const searchApi = {
  // Search books by terms (fuzzy search)
  // terms: array of search strings
  search: (terms) => api.post('/search', { terms }),
};
