// Generated by Claude.
// String normalization utilities for DynamoDB sort key generation.
// DynamoDB uses UTF-8 byte order sorting, which causes accented characters
// (É = 0xC3 0x89) to sort after all ASCII letters. This normalizer ensures
// consistent alphabetical sorting regardless of diacritics.
package persistence

import (
	"strings"
	"unicode"

	"golang.org/x/text/runes"
	"golang.org/x/text/transform"
	"golang.org/x/text/unicode/norm"
)

// NormalizeForMatching folds a string to its accent-free lowercase form.
// It removes diacritics (É→E, ñ→n) and converts to lowercase.
//
// Two jobs share this fold, and they are NOT the same job:
//   - DynamoDB sort keys (models.go), so listing order ignores accents
//   - the search index and its queries, via internal/searchindex.Fold
//
// What must be byte-identical is the search index and the search query — a
// query folded differently from the text it searches stops matching it, with
// no error anywhere. internal/searchindex guarantees that by calling one
// function for both.
//
// Sort keys merely happen to want the same accent handling. DO NOT add
// search-only behaviour here: internal/searchindex.Fold additionally splits
// French elisions, and pushing that down into this function would change the
// sort key of every item — reordering the browse stream and leaving every
// stored GSI1SK/GSI2SK stale until rewritten. That is a data migration, not a
// search-index resync. normalize_test.go guards the boundary.
func NormalizeForMatching(s string) string {
	// Step 1: NFD normalization separates base characters from combining marks
	// "É" becomes "E" + combining acute accent
	// Step 2: Remove combining marks (diacritics)
	// Step 3: NFC normalization recomposes any remaining sequences
	t := transform.Chain(
		norm.NFD,
		runes.Remove(runes.In(unicode.Mn)), // Mn = Mark, Nonspacing (combining diacritics)
		norm.NFC,
	)

	result, _, err := transform.String(t, s)
	if err != nil {
		// Fallback to original string if transformation fails
		return strings.ToLower(s)
	}

	return strings.ToLower(result)
}
