// Generated by Claude.
// String normalization utilities for DynamoDB sort key generation.
// DynamoDB uses UTF-8 byte order sorting, which causes accented characters
// (É = 0xC3 0x89) to sort after all ASCII letters. This normalizer ensures
// consistent alphabetical sorting regardless of diacritics.
package persistence

import (
	"strings"
	"unicode"

	"golang.org/x/text/runes"
	"golang.org/x/text/transform"
	"golang.org/x/text/unicode/norm"
)

// NormalizeForSort transforms a string for DynamoDB sort key usage.
// It removes diacritics (É→E, ñ→n) and converts to lowercase.
// This ensures proper alphabetical sorting regardless of accents.
func NormalizeForSort(s string) string {
	// Step 1: NFD normalization separates base characters from combining marks
	// "É" becomes "E" + combining acute accent
	// Step 2: Remove combining marks (diacritics)
	// Step 3: NFC normalization recomposes any remaining sequences
	t := transform.Chain(
		norm.NFD,
		runes.Remove(runes.In(unicode.Mn)), // Mn = Mark, Nonspacing (combining diacritics)
		norm.NFC,
	)

	result, _, err := transform.String(t, s)
	if err != nil {
		// Fallback to original string if transformation fails
		return strings.ToLower(s)
	}

	return strings.ToLower(result)
}
