# Generated by Claude.
# CloudWatch Log Groups with retention for Lambda functions

locals {
  log_retention_days = 7 # Adjust as needed: 1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1096, 1827, 2192, 2557, 2922, 3288, 3653
}

resource "aws_cloudwatch_log_group" "api" {
  name              = "/aws/lambda/${aws_lambda_function.api.function_name}"
  retention_in_days = local.log_retention_days
}

resource "aws_cloudwatch_log_group" "indexer" {
  name              = "/aws/lambda/${aws_lambda_function.indexer.function_name}"
  retention_in_days = local.log_retention_days
}

resource "aws_cloudwatch_log_group" "consistency_manager" {
  name              = "/aws/lambda/${aws_lambda_function.consistency_manager.function_name}"
  retention_in_days = local.log_retention_days
}

resource "aws_cloudwatch_log_group" "user_management" {
  name              = "/aws/lambda/${aws_lambda_function.user_management.function_name}"
  retention_in_days = local.log_retention_days
}

resource "aws_cloudwatch_log_group" "image_processor" {
  name              = "/aws/lambda/${aws_lambda_function.image_processor.function_name}"
  retention_in_days = local.log_retention_days
}
