# Generated by Claude.
# Cognito User Pool for Alexandria authentication

resource "aws_cognito_user_pool" "alexandria_user_pool" {
  name = "alexandria"

  username_configuration {
    case_sensitive = false
  }

  account_recovery_setting {
    recovery_mechanism {
      name     = "admin_only"
      priority = 1
    }
  }

  password_policy {
    minimum_length                   = 8
    require_lowercase                = true
    require_numbers                  = true
    require_symbols                  = true
    require_uppercase                = true
    temporary_password_validity_days = 7
  }

  user_pool_add_ons {
    advanced_security_mode = "OFF"
  }

  # Custom attributes
    schema {
    name                = "Id"
    attribute_data_type = "String"
    mutable             = true

    string_attribute_constraints {
      min_length = 1
      max_length = 50
    }
  }

  schema {
    name                = "Approved"
    attribute_data_type = "String"
    mutable             = true

    string_attribute_constraints {
      min_length = 1
      max_length = 5
    }
  }
}

resource "aws_cognito_user_pool_client" "alexandria_client" {
  name         = "alexandria-auth-client"
  user_pool_id = aws_cognito_user_pool.alexandria_user_pool.id

  explicit_auth_flows = [
    "ALLOW_USER_PASSWORD_AUTH",
    "ALLOW_REFRESH_TOKEN_AUTH",
    "ALLOW_USER_SRP_AUTH",
  ]

  # Attributes included in ID token
  read_attributes = [
    "custom:Id",
    "custom:Approved",
    "email",
    "name"
  ]

  write_attributes = []
}
