# Generated by Claude.
# DynamoDB table for Alexandria
# Single-table design with 2 GSIs for flexible access patterns

resource "aws_dynamodb_table" "alexandria" {
  name         = var.dynamodb_table_name
  billing_mode = "PAY_PER_REQUEST"
  table_class  = "STANDARD"

  # Primary key: composite key (PK + SK)
  hash_key  = "PK"
  range_key = "SK"

  # Stream for consistency-manager and index-items functions
  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  # Key attributes
  attribute {
    name = "PK"
    type = "S"
  }

  attribute {
    name = "SK"
    type = "S"
  }

  # GSI1 attributes - query-focused index
  attribute {
    name = "GSI1PK"
    type = "S"
  }

  attribute {
    name = "GSI1SK"
    type = "S"
  }

  # GSI2 attributes - owner-wide searches
  attribute {
    name = "GSI2PK"
    type = "S"
  }

  attribute {
    name = "GSI2SK"
    type = "S"
  }

  # GSI1: Query-focused access pattern
  global_secondary_index {
    name            = "GSI1"
    projection_type = "ALL"

    key_schema {
      attribute_name = "GSI1PK"
      key_type       = "HASH"
    }

    key_schema {
      attribute_name = "GSI1SK"
      key_type       = "RANGE"
    }
  }

  # GSI2: Owner-wide search access pattern
  global_secondary_index {
    name            = "GSI2"
    projection_type = "ALL"

    key_schema {
      attribute_name = "GSI2PK"
      key_type       = "HASH"
    }

    key_schema {
      attribute_name = "GSI2SK"
      key_type       = "RANGE"
    }
  }

}
