# Generated by Claude.
# ECR repository for images-processing Lambda

resource "aws_ecr_repository" "images_processing" {
  name                 = "alexandria/images-processing"
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration {
    scan_on_push = false
  }
}

resource "aws_ecr_lifecycle_policy" "images_processing" {
  repository = aws_ecr_repository.images_processing.name

  policy = jsonencode({
    rules = [
      {
        rulePriority = 1
        description  = "Expire untagged images older than 3 days"
        selection = {
          tagStatus   = "untagged"
          countType   = "sinceImagePushed"
          countUnit   = "days"
          countNumber = 3
        }
        action = {
          type = "expire"
        }
      }
    ]
  })
}
