# Generated by Claude.
# IAM roles for Lambda functions

data "aws_caller_identity" "current" {}
data "aws_region" "current" {}

locals {
  account_id = data.aws_caller_identity.current.account_id
  region     = data.aws_region.current.region
}

# Common assume role policy for Lambda
data "aws_iam_policy_document" "lambda_assume_role" {
  statement {
    effect = "Allow"
    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
    actions = ["sts:AssumeRole"]
  }
}

# Common CloudWatch Logs policy
data "aws_iam_policy_document" "cloudwatch_logs" {
  statement {
    effect = "Allow"
    actions = [
      "logs:CreateLogGroup",
      "logs:CreateLogStream",
      "logs:PutLogEvents",
      "logs:TagResource",
    ]
    resources = ["arn:aws:logs:${local.region}:${local.account_id}:log-group:/aws/lambda/*:*:*"]
  }
}

#
# API Role
#
resource "aws_iam_role" "api" {
  name               = "alexandria-api"
  assume_role_policy = data.aws_iam_policy_document.lambda_assume_role.json
}

data "aws_iam_policy_document" "api" {
  source_policy_documents = [data.aws_iam_policy_document.cloudwatch_logs.json]

  statement {
    effect = "Allow"
    actions = [
      "dynamodb:BatchExecuteStatement",
      "dynamodb:BatchGetItem",
      "dynamodb:BatchWriteItem",
      "dynamodb:DeleteItem",
      "dynamodb:ExecuteStatement",
      "dynamodb:ExecuteTransaction",
      "dynamodb:GetItem",
      "dynamodb:PutItem",
      "dynamodb:Query",
      "dynamodb:Scan",
      "dynamodb:TransactGetItems",
      "dynamodb:TransactWriteItems",
      "dynamodb:UpdateItem",
    ]
    resources = [
      aws_dynamodb_table.alexandria.arn,
      "${aws_dynamodb_table.alexandria.arn}/index/*",
    ]
  }

  statement {
    effect = "Allow"
    actions = [
      "s3:PutObject",
      "s3:PutObjectTagging",
      "s3:GetObject",
      "s3:ListBucket",
      "s3:GetObjectTagging",
      "s3:DeleteObject",
    ]
    resources = [
      aws_s3_bucket.alexandria.arn,
      "${aws_s3_bucket.alexandria.arn}/*",
    ]
  }

  statement {
    effect    = "Allow"
    actions   = ["cognito-idp:ListUsers"]
    resources = [aws_cognito_user_pool.alexandria_user_pool.arn]
  }

  statement {
    effect    = "Allow"
    actions   = ["rekognition:DetectText"]
    resources = ["*"]
  }

  statement {
    effect  = "Allow"
    actions = ["ssm:GetParameter"]
    resources = [
      "arn:aws:ssm:${local.region}:${local.account_id}:parameter/alexandria.lastevaluatedkey.secret",
      "arn:aws:ssm:${local.region}:${local.account_id}:parameter/alexandria.tmdb.access.token"
    ]
  }
}

resource "aws_iam_role_policy" "api" {
  name   = "alexandria-api"
  role   = aws_iam_role.api.id
  policy = data.aws_iam_policy_document.api.json
}

#
# Consistency Manager Role
#
resource "aws_iam_role" "consistency_manager" {
  name               = "alexandria-consistency-manager"
  assume_role_policy = data.aws_iam_policy_document.lambda_assume_role.json
}

data "aws_iam_policy_document" "consistency_manager" {
  source_policy_documents = [data.aws_iam_policy_document.cloudwatch_logs.json]

  statement {
    effect = "Allow"
    actions = [
      "dynamodb:BatchExecuteStatement",
      "dynamodb:BatchGetItem",
      "dynamodb:BatchWriteItem",
      "dynamodb:GetItem",
      "dynamodb:Query",
      "dynamodb:Scan",
      "dynamodb:TransactGetItems",
      "dynamodb:TransactWriteItems",
      "dynamodb:UpdateItem",
      "dynamodb:PartiQLUpdate",
    ]
    resources = [
      aws_dynamodb_table.alexandria.arn,
      "${aws_dynamodb_table.alexandria.arn}/index/*",
    ]
  }
}

resource "aws_iam_role_policy" "consistency_manager" {
  name   = "alexandria-consistency-manager"
  role   = aws_iam_role.consistency_manager.id
  policy = data.aws_iam_policy_document.consistency_manager.json
}

#
# Index Items Role
#
resource "aws_iam_role" "index_items" {
  name               = "alexandria-index-items"
  assume_role_policy = data.aws_iam_policy_document.lambda_assume_role.json
}

data "aws_iam_policy_document" "index_items" {
  source_policy_documents = [data.aws_iam_policy_document.cloudwatch_logs.json]

  statement {
    effect    = "Allow"
    actions   = ["dynamodb:Scan"]
    resources = [aws_dynamodb_table.alexandria.arn]
  }

  statement {
    effect = "Allow"
    actions = [
      "s3:PutObject",
      "s3:GetObject",
      "s3:ListBucket",
    ]
    resources = [
      aws_s3_bucket.alexandria.arn,
      "${aws_s3_bucket.alexandria.arn}/*",
    ]
  }
}

resource "aws_iam_role_policy" "index_items" {
  name   = "alexandria-index-items"
  role   = aws_iam_role.index_items.id
  policy = data.aws_iam_policy_document.index_items.json
}

#
# User Management Role
#
resource "aws_iam_role" "user_management" {
  name               = "alexandria-user-management"
  assume_role_policy = data.aws_iam_policy_document.lambda_assume_role.json
}

data "aws_iam_policy_document" "user_management" {
  source_policy_documents = [data.aws_iam_policy_document.cloudwatch_logs.json]

  statement {
    effect    = "Allow"
    actions   = ["sns:Publish"]
    resources = [data.aws_sns_topic.alerting.arn]
  }

  statement {
    effect = "Allow"
    actions = [
      "cognito-idp:AdminGetUser",
      "cognito-idp:AdminUpdateUserAttributes",
    ]
    resources = ["arn:aws:cognito-idp:${local.region}:${local.account_id}:userpool/*"]
  }
}

resource "aws_iam_role_policy" "user_management" {
  name   = "alexandria-user-management"
  role   = aws_iam_role.user_management.id
  policy = data.aws_iam_policy_document.user_management.json
}

#
# Images Processor Role
#
resource "aws_iam_role" "images_processor" {
  name               = "alexandria-images-processor"
  assume_role_policy = data.aws_iam_policy_document.lambda_assume_role.json
}

data "aws_iam_policy_document" "images_processor" {
  source_policy_documents = [data.aws_iam_policy_document.cloudwatch_logs.json]

  statement {
    effect = "Allow"
    actions = [
      "s3:GetObject",
      "s3:GetObjectTagging",
      "s3:PutObject",
      "s3:PutObjectTagging",
      "s3:ListBucket",
    ]
    resources = [
      aws_s3_bucket.alexandria.arn,
      "${aws_s3_bucket.alexandria.arn}/*",
    ]
  }
}

resource "aws_iam_role_policy" "images_processor" {
  name   = "alexandria-images-processor"
  role   = aws_iam_role.images_processor.id
  policy = data.aws_iam_policy_document.images_processor.json
}
