# Generated by Claude.
# IAM roles for Lambda functions

data "aws_caller_identity" "current" {}
data "aws_region" "current" {}

locals {
  account_id = data.aws_caller_identity.current.account_id
  region     = data.aws_region.current.region
}

#
# API Policy (role managed by lambda-function module)
#
data "aws_iam_policy_document" "api" {
  statement {
    effect = "Allow"
    actions = [
      "dynamodb:BatchExecuteStatement",
      "dynamodb:BatchGetItem",
      "dynamodb:BatchWriteItem",
      "dynamodb:DeleteItem",
      "dynamodb:ExecuteStatement",
      "dynamodb:ExecuteTransaction",
      "dynamodb:GetItem",
      "dynamodb:PutItem",
      "dynamodb:Query",
      "dynamodb:Scan",
      "dynamodb:TransactGetItems",
      "dynamodb:TransactWriteItems",
      "dynamodb:UpdateItem",
    ]
    resources = [
      aws_dynamodb_table.alexandria.arn,
      "${aws_dynamodb_table.alexandria.arn}/index/*",
    ]
  }

  statement {
    effect = "Allow"
    actions = [
      "s3:PutObject",
      "s3:PutObjectTagging",
      "s3:GetObject",
      "s3:ListBucket",
      "s3:GetObjectTagging",
      "s3:DeleteObject",
    ]
    resources = [
      aws_s3_bucket.alexandria.arn,
      "${aws_s3_bucket.alexandria.arn}/*",
    ]
  }

  statement {
    effect    = "Allow"
    actions   = ["cognito-idp:ListUsers"]
    resources = [aws_cognito_user_pool.alexandria_user_pool.arn]
  }

  statement {
    effect    = "Allow"
    actions   = ["rekognition:DetectText"]
    resources = ["*"]
  }

  statement {
    effect  = "Allow"
    actions = ["ssm:GetParameter"]
    resources = [
      "arn:aws:ssm:${local.region}:${local.account_id}:parameter/alexandria.lastevaluatedkey.secret",
      "arn:aws:ssm:${local.region}:${local.account_id}:parameter/alexandria.tmdb.access.token"
    ]
  }
}

resource "aws_iam_policy" "api" {
  name   = "alexandria-api"
  policy = data.aws_iam_policy_document.api.json
}

#
# Consistency Manager Policy (role managed by lambda-function module)
#
data "aws_iam_policy_document" "consistency_manager" {
  statement {
    effect = "Allow"
    actions = [
      "dynamodb:BatchExecuteStatement",
      "dynamodb:BatchGetItem",
      "dynamodb:BatchWriteItem",
      "dynamodb:GetItem",
      "dynamodb:Query",
      "dynamodb:Scan",
      "dynamodb:TransactGetItems",
      "dynamodb:TransactWriteItems",
      "dynamodb:UpdateItem",
      "dynamodb:PartiQLUpdate",
    ]
    resources = [
      aws_dynamodb_table.alexandria.arn,
      "${aws_dynamodb_table.alexandria.arn}/index/*",
    ]
  }
}

resource "aws_iam_policy" "consistency_manager" {
  name   = "alexandria-consistency-manager"
  policy = data.aws_iam_policy_document.consistency_manager.json
}

#
# Index Items Policy (role managed by lambda-function module)
#
data "aws_iam_policy_document" "index_items" {
  statement {
    effect    = "Allow"
    actions   = ["dynamodb:Scan"]
    resources = [aws_dynamodb_table.alexandria.arn]
  }

  statement {
    effect = "Allow"
    actions = [
      "s3:PutObject",
      "s3:GetObject",
      "s3:ListBucket",
    ]
    resources = [
      aws_s3_bucket.alexandria.arn,
      "${aws_s3_bucket.alexandria.arn}/*",
    ]
  }
}

resource "aws_iam_policy" "index_items" {
  name   = "alexandria-index-items"
  policy = data.aws_iam_policy_document.index_items.json
}

#
# User Management Policy (role managed by lambda-function module)
#
data "aws_iam_policy_document" "user_management" {
  statement {
    effect    = "Allow"
    actions   = ["sns:Publish"]
    resources = [data.aws_sns_topic.alerting.arn]
  }

  statement {
    effect = "Allow"
    actions = [
      "cognito-idp:AdminGetUser",
      "cognito-idp:AdminUpdateUserAttributes",
      "cognito-idp:AdminLinkProviderForUser",
      "cognito-idp:ListUsers",
    ]
    resources = ["arn:aws:cognito-idp:${local.region}:${local.account_id}:userpool/*"]
  }
}

resource "aws_iam_policy" "user_management" {
  name   = "alexandria-user-management"
  policy = data.aws_iam_policy_document.user_management.json
}

#
# Images Processor Policy (role managed by lambda-function module)
#
data "aws_iam_policy_document" "images_processor" {
  statement {
    effect = "Allow"
    actions = [
      "s3:GetObject",
      "s3:GetObjectTagging",
      "s3:PutObject",
      "s3:PutObjectTagging",
      "s3:ListBucket",
    ]
    resources = [
      aws_s3_bucket.alexandria.arn,
      "${aws_s3_bucket.alexandria.arn}/*",
    ]
  }
}

resource "aws_iam_policy" "images_processor" {
  name   = "alexandria-images-processor"
  policy = data.aws_iam_policy_document.images_processor.json
}
