# Generated by Claude.
# Terraform configuration for Alexandria infrastructure
# Deploy order: Terraform first → Serverless second

terraform {
  required_version = ">= 1.10.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
  }

  backend "s3" {
    bucket       = "global-tf-states"
    key          = "alexandria/terraform.tfstate"
    region       = "eu-central-1"
    use_lockfile = true # S3 native locking (no DynamoDB needed)
  }
}

provider "aws" {
  region = var.region

  default_tags {
    tags = {
      application = "alexandria"
      owner       = "terraform"
    }
  }
}

# Provider alias for CloudFront certificate (must be in us-east-1)
provider "aws" {
  alias  = "us_east_1"
  region = "us-east-1"

  default_tags {
    tags = {
      application = "alexandria"
      owner       = "terraform"
    }
  }
}
