# Generated by Claude.
# Outputs for Serverless Framework to reference via terraform:outputs



output "cognito_user_pool_id" {
  description = "ID of the Cognito User Pool"
  value       = aws_cognito_user_pool.alexandria_user_pool.id
}

output "cognito_user_pool_client_id" {
  description = "ID of the Cognito User Pool Client"
  value       = aws_cognito_user_pool_client.alexandria_client.id
}

output "cloudfront_distribution_id" {
  description = "ID of the CloudFront distribution for cache invalidation"
  value       = aws_cloudfront_distribution.main.id
}

output "api_endpoint" {
  description = "API Gateway endpoint URL for local development proxy"
  value       = module.api_trigger.api_endpoint
}

output "region" {
  value = data.aws_region.current.id
}

output "authentication_domain" {
  value = var.authentication_domain
}


