# Generated by Claude.
# S3 bucket for pictures and search index

resource "aws_s3_bucket" "alexandria" {
  bucket = "alexandria-items"
}

resource "aws_s3_bucket_lifecycle_configuration" "alexandria" {
  bucket = aws_s3_bucket.alexandria.id

  rule {
    id     = "IncomingPicturesRule"
    status = "Enabled"

    filter {
      prefix = "incoming"
    }

    expiration {
      days = 1
    }
  }
}

resource "aws_s3_bucket_public_access_block" "alexandria" {
  bucket = aws_s3_bucket.alexandria.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "alexandria" {
  bucket = aws_s3_bucket.alexandria.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}
