# Generated by Claude.
# S3 bucket for pictures and search index

resource "aws_s3_bucket" "alexandria" {
  bucket = "alexandria-items"
  # Allow `terraform destroy` to remove the bucket even when objects remain.
  force_destroy = true
}

resource "aws_s3_bucket_lifecycle_configuration" "alexandria" {
  bucket = aws_s3_bucket.alexandria.id

  rule {
    id     = "IncomingPicturesRule"
    status = "Enabled"

    filter {
      prefix = "incoming"
    }

    expiration {
      days = 1
    }
  }
}

resource "aws_s3_bucket_public_access_block" "alexandria" {
  bucket = aws_s3_bucket.alexandria.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "alexandria" {
  bucket = aws_s3_bucket.alexandria.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# Bucket policy to allow CloudFront OAC access to thumbnails
resource "aws_s3_bucket_policy" "alexandria_cloudfront" {
  bucket = aws_s3_bucket.alexandria.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "AllowCloudFrontOAC"
        Effect    = "Allow"
        Principal = {
          Service = "cloudfront.amazonaws.com"
        }
        Action   = "s3:GetObject"
        Resource = "${aws_s3_bucket.alexandria.arn}/user/*"
        Condition = {
          StringEquals = {
            "AWS:SourceArn" = aws_cloudfront_distribution.main.arn
          }
        }
      }
    ]
  })
}
