# Generated by Claude.
# Common variables for Alexandria infrastructure

variable "region" {
  description = "AWS region"
  type        = string
  default     = "eu-central-1"
}

variable "dynamodb_table_name" {
  description = "Name of the DynamoDB table"
  type        = string
  default     = "alexandria"
}

variable "authentication_domain" {
  description = "Domain for federated authentication"
  type        = string
  default     = "alexandria-auth.isnan.eu"
}
