// Generated by Claude.
const App = () => {
  return (
    <div className="flex min-h-svh items-center justify-center">
      <div className="text-center">
        <h1 className="text-4xl font-bold tracking-tight">Alexandria</h1>
        <p className="mt-2 text-muted-foreground">
          Manage your libraries and books
        </p>
      </div>
    </div>
  );
};

export default App;
