// Generated by Claude.
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import { Library, Search as SearchIcon, SlidersHorizontal } from 'lucide-react';
import { AuthProvider, useAuth } from '@/auth/AuthContext';
import { TabNavigator } from '@/navigation';
import Login from '@/pages/Login';
import Libraries from '@/pages/Libraries';
import Search from '@/pages/Search';
import Settings from '@/pages/Settings';

// Declarative screen configuration (React Navigation-inspired)
const screens = [
  {
    name: 'libraries',
    label: 'Libraries',
    icon: Library,
    component: Libraries,
    options: { title: 'My Libraries' },
  },
  {
    name: 'search',
    label: 'Search',
    icon: SearchIcon,
    component: Search,
    options: { title: 'Search' },
  },
  {
    name: 'settings',
    label: 'Settings',
    icon: SlidersHorizontal,
    component: Settings,
    options: { title: 'Settings' },
  },
];

// Redirects unauthenticated users to /login
const ProtectedRoute = ({ children }) => {
  const { isAuthenticated, isLoading } = useAuth();

  if (isLoading) return null;
  if (!isAuthenticated) return <Navigate to="/login" replace />;
  return children;
};

// Redirects already-authenticated users away from /login
const PublicRoute = ({ children }) => {
  const { isAuthenticated, isLoading } = useAuth();

  if (isLoading) return null;
  if (isAuthenticated) return <Navigate to="/" replace />;
  return children;
};

const App = () => (
  <BrowserRouter>
    <AuthProvider>
      <Routes>
        <Route
          path="/login"
          element={
            <PublicRoute>
              <Login />
            </PublicRoute>
          }
        />
        <Route
          path="/"
          element={
            <ProtectedRoute>
              <TabNavigator screens={screens} initialRoute="libraries" />
            </ProtectedRoute>
          }
        />
      </Routes>
    </AuthProvider>
  </BrowserRouter>
);

export default App;
