// Generated by Claude.
// Cognito & API config derived from CloudFormation stack outputs
import { alexandriaUserPoolId, alexandriaClientId } from '../output.json';

export const config = {
  userPoolId: alexandriaUserPoolId,
  clientId: alexandriaClientId,
  region: 'eu-central-1',
  apiBaseUrl: 'https://api-alexandria.isnan.eu',
};
