// Generated by Claude.
// AppBar: sticky header with centered title, back button slot, and right slot
import { ChevronLeft } from 'lucide-react';
import { cn } from '@/lib/utils';
import { useNavigation } from './NavigationContext';

const AppBar = ({ title, headerLeft, headerRight, showBackButton = 'auto', className }) => {
  const { canGoBack, goBack } = useNavigation();

  // Determine if back button should show: 'auto' uses canGoBack, or explicit boolean
  const shouldShowBack = showBackButton === 'auto' ? canGoBack : showBackButton;

  return (
    <header
      className={cn(
        'sticky top-0 z-50 h-14 border-b border-border bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60',
        className
      )}
    >
      <div className="flex h-full items-center px-4">
        {/* Left slot: back button or custom content */}
        <div className="flex w-12 justify-start">
          {headerLeft ?? (
            shouldShowBack && (
              <button
                onClick={goBack}
                className="flex h-9 w-9 items-center justify-center rounded-md text-muted-foreground hover:bg-accent hover:text-accent-foreground"
                aria-label="Go back"
              >
                <ChevronLeft className="h-5 w-5" />
              </button>
            )
          )}
        </div>

        {/* Center: title */}
        <h1 className="flex-1 text-center text-lg font-semibold truncate">
          {title}
        </h1>

        {/* Right slot: reserved for future actions */}
        <div className="flex w-12 justify-end">
          {headerRight}
        </div>
      </div>
    </header>
  );
};

export default AppBar;
