// Generated by Claude.
// AppBar: simple header component rendered by each page
// Props-based configuration, no shared state
import { useNavigate, useLocation } from 'react-router-dom';
import { ChevronLeft } from 'lucide-react';
import { cn } from '@/lib/utils';

// Tab root paths - these don't show back button by default
const TAB_PATHS = ['/libraries', '/search', '/settings'];

const AppBar = ({
  title,
  subtitle,
  headerLeft,
  headerRight,
  onTitleClick,
  className,
}) => {
  const navigate = useNavigate();
  const location = useLocation();

  // Show back button unless we're on a tab root or headerLeft is explicitly provided
  const isTabRoot = TAB_PATHS.includes(location.pathname);
  const showBackButton = !isTabRoot && headerLeft === undefined;

  const handleBack = () => {
    navigate(-1);
  };

  return (
    <header
      className={cn(
        'sticky top-0 z-50 shrink-0 border-b border-border bg-background',
        subtitle ? 'h-16' : 'h-14',
        className
      )}
    >
      <div className="flex h-full items-center px-4">
        {/* Left slot: back button, custom content, or empty */}
        <div className="flex w-12 justify-start">
          {headerLeft ?? (
            showBackButton && (
              <button
                onClick={handleBack}
                className="flex h-9 w-9 items-center justify-center rounded-md text-muted-foreground hover:bg-accent hover:text-accent-foreground"
                aria-label="Go back"
              >
                <ChevronLeft className="h-5 w-5" />
              </button>
            )
          )}
        </div>

        {/* Center: title + optional subtitle */}
        <button
          type="button"
          onClick={onTitleClick}
          disabled={!onTitleClick}
          className={cn(
            'flex-1 min-w-0 flex flex-col items-center justify-center bg-transparent border-none',
            onTitleClick ? 'cursor-pointer active:opacity-70' : 'cursor-default'
          )}
          aria-label={onTitleClick ? 'Scroll to top' : undefined}
        >
          <span className="text-lg font-semibold truncate w-full text-center">{title}</span>
          {subtitle && (
            <span className="text-xs text-muted-foreground truncate w-full text-center">{subtitle}</span>
          )}
        </button>

        {/* Right slot */}
        <div className="flex w-12 justify-end">
          {headerRight}
        </div>
      </div>
    </header>
  );
};

export default AppBar;
