// Generated by Claude.
// BottomTabs: sticky footer navigation with declarative tab configuration
import { cn } from '@/lib/utils';
import { useNavigation } from './NavigationContext';

const BottomTabs = ({ tabs, className }) => {
  const { currentRoute, navigate } = useNavigation();

  return (
    <nav
      className={cn(
        'sticky bottom-0 z-50 border-t border-border bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60',
        className
      )}
    >
      <div className="flex h-16 items-center justify-around px-2">
        {tabs.map((tab) => {
          const isActive = currentRoute === tab.name;
          const Icon = tab.icon;

          return (
            <button
              key={tab.name}
              onClick={() => navigate(tab.name)}
              className={cn(
                'flex flex-1 flex-col items-center justify-center gap-1 py-2 transition-colors',
                isActive
                  ? 'text-primary'
                  : 'text-muted-foreground hover:text-foreground'
              )}
              aria-current={isActive ? 'page' : undefined}
            >
              {Icon && <Icon className="h-5 w-5" />}
              <span className="text-xs font-medium">{tab.label}</span>
            </button>
          );
        })}
      </div>
    </nav>
  );
};

export default BottomTabs;
