// Generated by Claude.
// Navigation context: provides declarative navigation state management
// Inspired by React Navigation's approach to screen/tab configuration
import { createContext, useContext, useState, useMemo, useCallback } from 'react';

const NavigationContext = createContext(null);

export const NavigationProvider = ({ children, initialRoute = null }) => {
  const [currentRoute, setCurrentRoute] = useState(initialRoute);
  const [navigationStack, setNavigationStack] = useState([]);
  const [screenOptions, setScreenOptions] = useState({});
  const [routeParams, setRouteParams] = useState(null);

  // Navigate to a route, optionally pushing to stack for back navigation
  const navigate = useCallback((route, options = {}) => {
    if (options.push) {
      setNavigationStack((prev) => [...prev, currentRoute]);
    }
    setCurrentRoute(route);
    setRouteParams(options.params || null);
    // Reset screen options when navigating
    setScreenOptions({});
  }, [currentRoute]);

  // Go back to previous screen in stack
  const goBack = useCallback(() => {
    if (navigationStack.length > 0) {
      const prevRoute = navigationStack[navigationStack.length - 1];
      setNavigationStack((prev) => prev.slice(0, -1));
      setCurrentRoute(prevRoute);
      setRouteParams(null);
      return true;
    }
    return false;
  }, [navigationStack]);

  // Check if we can go back
  const canGoBack = navigationStack.length > 0;

  // Allow screens to set their options (title, headerRight, etc.)
  const setOptions = useCallback((options) => {
    setScreenOptions((prev) => ({ ...prev, ...options }));
  }, []);

  const value = useMemo(() => ({
    currentRoute,
    params: routeParams,
    navigate,
    goBack,
    canGoBack,
    screenOptions,
    setOptions,
  }), [currentRoute, routeParams, navigate, goBack, canGoBack, screenOptions, setOptions]);

  return (
    <NavigationContext.Provider value={value}>
      {children}
    </NavigationContext.Provider>
  );
};

export const useNavigation = () => {
  const context = useContext(NavigationContext);
  if (!context) {
    throw new Error('useNavigation must be used within a NavigationProvider');
  }
  return context;
};
