// Generated by Claude.
// TabNavigator: declarative tab-based navigation container
// Combines AppBar + content area + BottomTabs into a cohesive layout
import { useMemo } from 'react';
import { NavigationProvider, useNavigation } from './NavigationContext';
import AppBar from './AppBar';
import BottomTabs from './BottomTabs';

// Internal component that renders current screen
const TabContent = ({ screens }) => {
  const { currentRoute, screenOptions } = useNavigation();

  const currentScreen = useMemo(() => {
    return screens.find((s) => s.name === currentRoute);
  }, [screens, currentRoute]);

  if (!currentScreen) return null;

  const Component = currentScreen.component;
  const title = screenOptions.title ?? currentScreen.options?.title ?? currentScreen.label;

  return (
    <div className="flex min-h-svh flex-col">
      <AppBar
        title={title}
        headerLeft={screenOptions.headerLeft}
        headerRight={screenOptions.headerRight}
        showBackButton={screenOptions.showBackButton}
      />

      {/* Main content area: fills space between header and footer */}
      <main className="flex-1 overflow-auto">
        <Component />
      </main>

      <BottomTabs
        tabs={screens.map((s) => ({
          name: s.name,
          label: s.label,
          icon: s.icon,
        }))}
      />
    </div>
  );
};

// Main TabNavigator: wraps everything in NavigationProvider
const TabNavigator = ({ screens, initialRoute }) => {
  // Default to first screen if no initial route
  const defaultRoute = initialRoute ?? screens[0]?.name;

  return (
    <NavigationProvider initialRoute={defaultRoute}>
      <TabContent screens={screens} />
    </NavigationProvider>
  );
};

export default TabNavigator;
