// Generated by Claude.
// TabNavigator: declarative tab-based navigation container
// Supports both tab screens (with bottom tabs) and stack screens (pushed on top)
import { useMemo } from 'react';
import { NavigationProvider, useNavigation } from './NavigationContext';
import AppBar from './AppBar';
import BottomTabs from './BottomTabs';

// Internal component that renders current screen
const TabContent = ({ screens, stackScreens = [] }) => {
  const { currentRoute, screenOptions, canGoBack } = useNavigation();

  // Check if current route is a stack screen (no tabs)
  const stackScreen = useMemo(() => {
    return stackScreens.find((s) => s.name === currentRoute);
  }, [stackScreens, currentRoute]);

  // Check if current route is a tab screen
  const tabScreen = useMemo(() => {
    return screens.find((s) => s.name === currentRoute);
  }, [screens, currentRoute]);

  const currentScreen = stackScreen || tabScreen;
  if (!currentScreen) return null;

  const Component = currentScreen.component;
  const title = screenOptions.title ?? currentScreen.options?.title ?? currentScreen.label;
  const isStackScreen = !!stackScreen;
  // Show tabs for tab screens, or stack screens with showTabs: true
  const shouldShowTabs = !isStackScreen || stackScreen?.options?.showTabs;

  return (
    <div className="flex min-h-svh flex-col">
      <AppBar
        title={title}
        headerLeft={screenOptions.headerLeft}
        headerRight={screenOptions.headerRight}
        showBackButton={isStackScreen ? true : (screenOptions.showBackButton ?? canGoBack)}
      />

      {/* Main content area - relative for absolute positioned children */}
      <main className="flex-1 overflow-hidden relative">
        <Component />
      </main>

      {/* Show tabs for tab screens or stack screens with showTabs option */}
      {shouldShowTabs && (
        <BottomTabs
          tabs={screens.map((s) => ({
            name: s.name,
            label: s.label,
            icon: s.icon,
          }))}
        />
      )}
    </div>
  );
};

// Main TabNavigator: wraps everything in NavigationProvider
const TabNavigator = ({ screens, stackScreens, initialRoute }) => {
  // Default to first screen if no initial route
  const defaultRoute = initialRoute ?? screens[0]?.name;

  return (
    <NavigationProvider initialRoute={defaultRoute}>
      <TabContent screens={screens} stackScreens={stackScreens} />
    </NavigationProvider>
  );
};

export default TabNavigator;
