// Generated by Claude.
// Navigation helper hook: lookup item by IDs from LibrariesContext
// Bridges URL params to context data
import { useMemo } from 'react';
import { useLibraries } from '@/state';
import { useLibraryData } from './useLibraryData';

/**
 * Look up item data by library and item IDs from LibrariesContext
 * @param {string} libraryId - Library ID from URL params
 * @param {string} itemId - Item ID from URL params
 * @returns {{ item: object|null, library: object|null, isSharedLibrary: boolean, isLoading: boolean }}
 */
export const useItemData = (libraryId, itemId) => {
  const { library, isSharedLibrary, isLoading: isLibraryLoading } = useLibraryData(libraryId);
  const { itemsByLibrary } = useLibraries();

  const itemsState = itemsByLibrary[libraryId];
  const items = itemsState?.items || [];
  const isItemsLoading = itemsState?.isLoading || false;

  const item = useMemo(() => {
    if (!itemId) return null;
    return items.find((i) => i.id === itemId) || null;
  }, [items, itemId]);

  return {
    item,
    library,
    isSharedLibrary,
    isLoading: isLibraryLoading || isItemsLoading,
  };
};
