// Generated by Claude.
// Navigation helper hook: lookup item by IDs from LibrariesContext
// Bridges URL params to context data
import { useMemo } from 'react';
import { useLibraries } from '@/state';
import { useLibraryData } from './useLibraryData';

/**
 * Look up item data by library and item IDs from LibrariesContext
 * @param {string} libraryId - Library ID from URL params
 * @param {string} itemId - Item ID from URL params
 * @returns {{ item: object|null, library: object|null, isSharedLibrary: boolean, isLoading: boolean }}
 */
export const useItemData = (libraryId, itemId) => {
  const { library, isSharedLibrary, isLoading: isLibraryLoading } = useLibraryData(libraryId);
  const { itemsByLibrary } = useLibraries();

  const itemsState = itemsByLibrary[libraryId];
  const isItemsLoading = itemsState?.isLoading || false;

  const item = useMemo(() => {
    const items = itemsState?.items || [];
    if (!itemId) return null;
    // Search top-level items first
    const topLevel = items.find((i) => i.id === itemId);
    if (topLevel) return topLevel;
    // Search inside collections (type=2 have nested items array)
    for (const i of items) {
      if (i.type === 2 && i.items) {
        const nested = i.items.find((ni) => ni.id === itemId);
        if (nested) return nested;
      }
    }
    return null;
  }, [itemsState?.items, itemId]);

  return {
    item,
    library,
    isSharedLibrary,
    isLoading: isLibraryLoading || isItemsLoading,
  };
};
