// Generated by Claude.
// Navigation helper hook: lookup library by ID from LibrariesContext
// Bridges URL params to context data
import { useMemo } from 'react';
import { useLibraries } from '@/state';

/**
 * Look up library data by ID from LibrariesContext
 * @param {string} libraryId - Library ID from URL params
 * @returns {{ library: object|null, isSharedLibrary: boolean, isLoading: boolean }}
 */
export const useLibraryData = (libraryId) => {
  const { libraries, isLoading, hasLoaded } = useLibraries();

  const library = useMemo(() => {
    if (!libraryId) return null;
    return libraries.find((lib) => lib.id === libraryId) || null;
  }, [libraries, libraryId]);

  const isSharedLibrary = !!library?.sharedFrom;

  return {
    library,
    isSharedLibrary,
    isLoading: !hasLoaded && isLoading,
  };
};
