// Generated by Claude.
// Hook to manage onboarding state via localStorage
import { useState, useCallback } from 'react';

const STORAGE_KEY = 'alexandria_onboarding_complete';

/**
 * Hook to check and manage onboarding completion state.
 * Uses localStorage to persist across sessions.
 *
 * @returns {{ showOnboarding: boolean, completeOnboarding: () => void, resetOnboarding: () => void }}
 */
export const useOnboarding = () => {
  // Initialize from localStorage - show onboarding if not completed
  const [showOnboarding, setShowOnboarding] = useState(() => {
    try {
      return localStorage.getItem(STORAGE_KEY) !== 'true';
    } catch {
      // localStorage unavailable (SSR, private browsing)
      return false;
    }
  });

  // Mark onboarding as complete
  const completeOnboarding = useCallback(() => {
    try {
      localStorage.setItem(STORAGE_KEY, 'true');
    } catch {
      // Silently fail if localStorage unavailable
    }
    setShowOnboarding(false);
  }, []);

  // Reset onboarding (for testing/debugging via console)
  const resetOnboarding = useCallback(() => {
    try {
      localStorage.removeItem(STORAGE_KEY);
    } catch {
      // Silently fail if localStorage unavailable
    }
    setShowOnboarding(true);
  }, []);

  return { showOnboarding, completeOnboarding, resetOnboarding };
};
