// Generated by Claude.
// DynamoDB client for direct AWS SDK access to the Alexandria table.
package dynamodb

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
)

// Item is a raw table row with PK/SK/EntityType lifted out for convenience.
type Item struct {
	PK         string
	SK         string
	EntityType string
	Attributes map[string]types.AttributeValue
}

type Client struct {
	client    *dynamodb.Client
	tableName string
}

func NewClient(ctx context.Context, region, tableName string) (*Client, error) {
	cfg, err := config.LoadDefaultConfig(ctx, config.WithRegion(region))
	if err != nil {
		return nil, fmt.Errorf("loading AWS config: %w", err)
	}
	return &Client{
		client:    dynamodb.NewFromConfig(cfg),
		tableName: tableName,
	}, nil
}

func toItem(raw map[string]types.AttributeValue) Item {
	it := Item{Attributes: raw}
	if v, ok := raw["PK"].(*types.AttributeValueMemberS); ok {
		it.PK = v.Value
	}
	if v, ok := raw["SK"].(*types.AttributeValueMemberS); ok {
		it.SK = v.Value
	}
	if v, ok := raw["EntityType"].(*types.AttributeValueMemberS); ok {
		it.EntityType = v.Value
	}
	return it
}

// QueryByPK returns every row under a partition key.
func (c *Client) QueryByPK(ctx context.Context, pk string) ([]Item, error) {
	var items []Item
	var lastKey map[string]types.AttributeValue

	for {
		resp, err := c.client.Query(ctx, &dynamodb.QueryInput{
			TableName:              aws.String(c.tableName),
			KeyConditionExpression: aws.String("#pk = :pk"),
			ExpressionAttributeNames: map[string]string{
				"#pk": "PK",
			},
			ExpressionAttributeValues: map[string]types.AttributeValue{
				":pk": &types.AttributeValueMemberS{Value: pk},
			},
			ExclusiveStartKey: lastKey,
		})
		if err != nil {
			return nil, fmt.Errorf("querying DynamoDB: %w", err)
		}
		for _, raw := range resp.Items {
			items = append(items, toItem(raw))
		}
		if resp.LastEvaluatedKey == nil {
			break
		}
		lastKey = resp.LastEvaluatedKey
	}
	return items, nil
}

// Scan returns all rows matching filter (empty filter = full scan).
func (c *Client) Scan(ctx context.Context, filter string, names map[string]string, values map[string]types.AttributeValue) ([]Item, error) {
	var items []Item
	var lastKey map[string]types.AttributeValue

	for {
		input := &dynamodb.ScanInput{
			TableName:         aws.String(c.tableName),
			ExclusiveStartKey: lastKey,
		}
		if filter != "" {
			input.FilterExpression = aws.String(filter)
			input.ExpressionAttributeValues = values
			if len(names) > 0 {
				input.ExpressionAttributeNames = names
			}
		}
		resp, err := c.client.Scan(ctx, input)
		if err != nil {
			return nil, fmt.Errorf("scanning DynamoDB: %w", err)
		}
		for _, raw := range resp.Items {
			items = append(items, toItem(raw))
		}
		if resp.LastEvaluatedKey == nil {
			break
		}
		lastKey = resp.LastEvaluatedKey
	}
	return items, nil
}

// DeleteItems batch-deletes items by PK/SK (25/batch, retries unprocessed).
func (c *Client) DeleteItems(ctx context.Context, items []Item) error {
	if len(items) == 0 {
		return nil
	}
	const batchSize = 25
	for i := 0; i < len(items); i += batchSize {
		end := i + batchSize
		if end > len(items) {
			end = len(items)
		}
		var writes []types.WriteRequest
		for _, item := range items[i:end] {
			writes = append(writes, types.WriteRequest{
				DeleteRequest: &types.DeleteRequest{
					Key: map[string]types.AttributeValue{
						"PK": &types.AttributeValueMemberS{Value: item.PK},
						"SK": &types.AttributeValueMemberS{Value: item.SK},
					},
				},
			})
		}
		input := &dynamodb.BatchWriteItemInput{
			RequestItems: map[string][]types.WriteRequest{c.tableName: writes},
		}
		for {
			resp, err := c.client.BatchWriteItem(ctx, input)
			if err != nil {
				return fmt.Errorf("batch deleting items: %w", err)
			}
			if len(resp.UnprocessedItems) == 0 {
				break
			}
			input.RequestItems = resp.UnprocessedItems
		}
	}
	return nil
}
