// Generated by Claude.
// Utility to hide the splash screen with a fade-out animation

// Build hash injected by Vite at build time
const BUILD_HASH = typeof __BUILD_HASH__ !== 'undefined' ? __BUILD_HASH__ : 'dev';

// Show build number on splash screen
export const showBuildOnSplash = () => {
  const buildEl = document.getElementById('splash-build');
  if (buildEl) {
    buildEl.textContent = `Build ${BUILD_HASH}`;
  }
};

export const hideSplash = () => {
  const splash = document.getElementById('splash');
  if (!splash) return;

  // Add fade-out class, then remove element after transition
  splash.classList.add('fade-out');
  setTimeout(() => {
    splash.remove();
  }, 300);
};
