// Generated by Claude.
// Utility to hide the splash screen with a fade-out animation

export const hideSplash = () => {
  const splash = document.getElementById('splash');
  if (!splash) return;

  // Add fade-out class, then remove element after transition
  splash.classList.add('fade-out');
  setTimeout(() => {
    splash.remove();
  }, 300);
};
