// Generated by Claude.
// shadcn/ui utility: merges Tailwind classes with conflict resolution
import { clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export const cn = (...inputs) => twMerge(clsx(inputs));
